### ISSUE TITLE
`+list-fonts` action should not list bitmap fonts

### ISSUE THREAD

**Issue by Cylis-Dragneel** [ghostty-org/ghostty#2168]
A couple of bitmap fonts, particularly those with the .otb format do not work in ghostty. Other bitmap fonts that use the .ttf file format do work though. 
So I suggest, at least until supporting .otb is a priority: remove any .otb fonts to be listed when running `ghostty +list-fonts` so as to not give false hopes

**Comment by apetresc** [comment]
They are showing up - I can confirm that, e.g., Terminus (in both OTB and PCF formats) shows up in `ghostty +list-formats` but then promptly crashes the terminal on launch :(

Out of curiosity, is this lack of support for bitmap fonts a permanent stance, or just a "haven't-gotten-around-to-it-yet" thing? Bitmap fonts like Terminus are so valuable in a terminal for me :(

**Comment by jcollie** [comment]
> Out of curiosity, is this lack of support for bitmap fonts a permanent stance, or just a "haven't-gotten-around-to-it-yet" thing? Bitmap fonts like Terminus are so valuable in a terminal for me :(

I wouldn't say it's a permanent stance, but it's very very low priority for any current developer. Anyone is welcome to contribute a fix though, as long as it doesn't complicate vector font handling too much. Be sure to read the CONTRIBUTING.md in the repo first though.

**Comment by mitchellh** [comment]
> Out of curiosity, is this lack of support for bitmap fonts a permanent stance, or just a "haven't-gotten-around-to-it-yet" thing? Bitmap fonts like Terminus are so valuable in a terminal for me :(

From another thread:

> You can get pixel perfect bitmap fonts by using their TrueType conversions and using fractional point font sizes. There are dozens of bitmap enthusiasts that were in the beta and they're totally convinced because well... it's pixel identical.
>
> I've noted before in issues I'm open to supporting bitmap fonts if someone contributes it, but not interested in adding it myself. The workaround above is very good.

There is a terminus TTF. If you set the proper font size, I'm quite confident you can get pixel perfect matching.

**Comment by def-** [comment]
> There is a terminus TTF. If you set the proper font size, I'm quite confident you can get pixel perfect matching.

I'm struggling with this on a low DPI screen on macOS:
![Image](https://github.com/user-attachments/assets/20acd8d1-47ef-459f-9d65-25abe4b97f17)

Top is iTerm2 with anti-aliasing disabled:
![Image](https://github.com/user-attachments/assets/3643e8ad-fb4f-4300-8c16-ee3c18a7aafc)

Bottom is Ghostty 1.0.0 with
```
font-family = "Terminus (TTF)"
font-size = 16
font-thicken = false
window-padding-x = 0
window-padding-y = 0
window-inherit-font-size = false
```
How would you find the exact font size required? Does it depend on screen DPI?

(I'm not sure if this warrants a separate issue or is just a user error from my side)

**Comment by sin-ack** [comment]
> Edit: This is probably fixed by https://github.com/ghostty-org/ghostty/pull/3837

Unfortunately not, since the change is in the Freetype renderer (which I presume you're not using as you're on a Mac).

**Comment by mitchellh** [comment]
Bitmap fonts are now supported on both macOS (#4115) and Linux (#3837)
