### ISSUE TITLE
Ghostty Resizes oddly when using Aerospace

### ISSUE THREAD

**Issue by maxcroy1** [ghostty-org/ghostty#3140]
I use Aerospace as my window manager on macOS, and I noticed that when a new tab on Ghostty is created, it seems like Aerospace registers this as a new window being opened and shifts the entire terminal to the side of the screen. 

Could be an Aerospace specific issue, but it seems to me like Ghostty is likely registering tabs as a new window errantly. I'm not an expert here, so feel free to let me know if this should be ignored :D 

Screen recording below. Let me know your thoughts!

**Comment by mitchellh** [comment]
This is a duplicate and is a macOS bug (or feature, but in any case it's dictated by macOS). Please search, its been well discussed and the Aerospace creator was a long-time private beta tester.
