### ISSUE TITLE
macoS: Opening a new tab is detected by yabai as opening a new window

### ISSUE THREAD

**Issue by jackbashford** [ghostty-org/ghostty#3155]
I use [yabai](https://github.com/koekeishiya/yabai) for managing windows, and when I open a new tab, yabai reacts as though I've opened a new window, and halves the space that ghostty takes up (the other half being dedicated to the new invisible 'window').

I haven't encountered this problem with other applications that have native tabs (e.g. iTerm2) so I believe it is an issue with how ghostty presents opening a tab to macOS (I'm unfamiliar with the codebase and window management system so may not be using the appropriate terminology here, I apologise.)

Reproduction steps: Install yabai (don't think SIP disabling is necessary as this appears to just be a single-space window arrangement feature) and ghostty, and open a new tab in a ghostty instance.

See below where I open tabs to create new 'windows' (forcing the resize), then close them and destroy those 'windows'.
![Image](https://github.com/user-attachments/assets/52d9076e-9e30-4a42-bb6a-1beac8135bdb)

**Comment by mitchellh** [comment]
Dupe search for it please, this is well covered. I'll add it to the common issues of the website too.

This is a macOS bug or feature. In any case we can't do anything about it.
