### ISSUE TITLE
Creating new tab splits the screen with aerospace

### ISSUE THREAD

**Issue by ericlake** [ghostty-org/ghostty#3170]
I am not sure if this is a ghostty issue or an aerospace tiling window manager issue. With ghostty running in its own window in aerospace if I hit cmd+t to create a new tab the window acts as if a new app has started and the instead of using the whole screen it splits to half the width. I do get a new tab though which is nice. When I kill this tab the window goes back to the expected size. With each new tab the window halves in size.

**Comment by mitchellh** [comment]
Please search. This gets asked so much!

**Comment by ivarref** [comment]
For those landing here: The problem and workaround is described [here](https://ghostty.org/docs/help/macos-tiling-wms#workarounds).

I needed to put:

```
[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= [
  "layout floating",
]
```

at the end of `$HOME/.config/aerospace/aerospace.toml`

The issue at aerospace [is here](https://github.com/nikitabobko/AeroSpace/issues/68).

**Comment by nkapila6** [comment]
> For those landing here: The problem and workaround is described [here](https://ghostty.org/docs/help/macos-tiling-wms#workarounds).
> [[on-window-detected]]
> if.app-id="com.mitchellh.ghostty"
> run= [
>   "layout floating",
> ]
> ```
> 
> at the end of `$HOME/.config/aerospace/aerospace.toml`

I know ghostty is not to blame here but this config just makes the window floating. If you open a new window, it does not move back to tiling.

Perhaps, I could look into changing the cmd+T keymap to opening new windows instead of tabs as a workaround but wish aerospace could distinguish better.

Thanks anyway!
