### ISSUE TITLE
macOS: ability to disable auto-update on source-built builds

### ISSUE THREAD

**Issue by prasincs** [ghostty-org/ghostty#3179]
OS: OSX 14.2 Sonoma
Commit Built From: [4b4d4062](https://github.com/ghostty-org/ghostty/commits/4b4d4062dfed7b37424c7210d1230242c709e990)

I built Ghostty from source using the commit above but on first start, it checks for version, seems to find 0.1 and says there's a new build.
<img width="799" alt="Image" src="https://github.com/user-attachments/assets/5af7d243-9fa5-4d38-a59f-f4123d223400" />
Is there a way to turn it off if I intend to build it from source?

**Comment by mitchellh** [comment]
Good idea, we should add the ability to disable Sparkle on source-built binaries. I think we can probably do this by simply changing the default Info.plist with the `ReleaseLocal` scheme in Xcode...

**Comment by prasincs** [comment]
> Good idea, we should add the ability to disable Sparkle on source-built binaries. I think we can probably do this by simply changing the default Info.plist with the `ReleaseLocal` scheme in Xcode...

not familiar with Xcode enough whether this requires creating a whole new Info.plist file or not
Maybe another option is to update here and not return a string if there's a way to know it's local? https://github.com/ghostty-org/ghostty/blob/35b9ceee2116331b83c0c86269394e2545070b0f/macos/Sources/Features/Update/UpdateDelegate.swift#L15

**Comment by curtbushko** [comment]
Do you still get the update if you have `auto-update = off` in your config?

**Comment by mitchellh** [comment]
> Do you still get the update if you have `auto-update = off` in your config?

This should resolve it, but I want to default this for source builds.

**Comment by prasincs** [comment]
> Do you still get the update if you have `auto-update = off` in your config?

thanks that resolved it for now
