### ISSUE TITLE
macOS: CFBundleShortVersionString is not strictly a version number, making it hard to compare across versions

### ISSUE THREAD

**Issue by discentem** [ghostty-org/ghostty#3204]
[Autopkg](https://github.com/autopkg/autopkg), a tool used by many large enterprise companies to maintain internal-only app stores, often relies on `CFBundleShortVersionString` to be numerical so it can determine if the version number for some piece of macOS software has increased. 

Right now it seems [`CFBundleShortVersionString` in Ghostty is set to commit hash](https://github.com/ghostty-org/ghostty/blob/main/.github/workflows/release-tag.yml#L164C44-L164C70) which makes it difficult for Autopkg to determine if a download of Ghostty is newer or not. 

Autopkg is quite flexible and can be made to use basically any alternative mechanism for finding the version string (shell out to `--version`, query an api, read and parse any file on disk, etc) if `CFBundleShortVersionString` won't increase in the future but it's not clear what alternative version string I should follow. 

Any suggestions/advice for where to look for a numerically increasing version number? I see `--version` does include `1.0.0-$COMMIT_HASH`. Can I assume the next tagged release will be `1.0.1-$COMMIT_HASH`? If so I can use that, though `CFBundleShortVersionString` would be preferred.

Edit: Thinking about this more, this problem might only exist _temporarily_ while the only release is the nightly. 😅 If that's the case, we can probably just close this without any change.

**Comment by mitchellh** [comment]
> Edit: Thinking about this more, this problem might only exist temporarily while the only release is the nightly. 😅 If that's the case, we can probably just close this without any change.

Tagged releases use a monotonically increasing build number for `CFBundleVersion`. The `ShortVersionString` has a string value. This is in line with how Apple documents these fields as far as I know. The short version string is supposed to be a human friendly "string" (in the name!) value and the build version is something internal. 

I think you should rely on `CFBundleVersion`.

If this understanding is incorrect I'm happy for someone to correct me.

**Comment by discentem** [comment]
> > Edit: Thinking about this more, this problem might only exist temporarily while the only release is the nightly. 😅 If that's the case, we can probably just close this without any change.
> 
> Tagged releases use a monotonically increasing build number for `CFBundleVersion`. The `ShortVersionString` has a string value. This is in line with how Apple documents these fields as far as I know. The short version string is supposed to be a human friendly "string" (in the name!) value and the build version is something internal.
> 
> I think you should rely on `CFBundleVersion`.
> 
> If this understanding is incorrect I'm happy for someone to correct me.

Thanks for the reply! 

Given that the [default behavior in Autopkg for `.app`](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/Versioner.py#L55) is to rely on `CFBundleShortVersionString` I'm assuming on average software packages generally have a monotonically increasing build number in `CFBundleShortVersionString`. This may be at odds with Apple's documentation though as you pointed out.

For what it's worth, in both https://release.files.ghostty.org/1.0.0/Ghostty.dmg and https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg `CFBundleVersion` is currently set to `8469` which for me is not obviously a version number. 

`CFBundleShortVersionString` actually looks how I expect in `https://release.files.ghostty.org/1.0.0/Ghostty.dmg` but this brings up another issue: is there an endpoint like `https://release.files.ghostty.org/latest/Ghostty.dmg` which would always point to the latest tagged version (not `tip`)? If not, that is okay too as I can just search https://ghostty.org/download for the link. Right now [I am relying on the Github Release assets](https://github.com/autopkg/discentem-recipes/blob/dff44e5581e16b9ddf9be8faedd9acbecdfd6849/Ghostty/ghostty.download.recipe.yaml#L11) but I guess that won't necessarily contain properly versioned releases

**Comment by discentem** [comment]
TL:DR No changes required to Ghostty versioning unless you'd like to. As of https://github.com/autopkg/discentem-recipes/blob/1a6d99928c4f6f82c7c19fd01c7f8318186f1623/Ghostty/ghostty.download.recipe.yaml#L12 I'm parsing  https://ghostty.org/download for the link to latest version.

**Comment by mitchellh** [comment]
Thanks. I will look into supporting a `latest`.
