### ISSUE TITLE
Ghost-Windows on macOS with global `toggle-visibility` keybind.

### ISSUE THREAD

**Issue by cpojer** [ghostty-org/ghostty#3219]
Thanks for building Ghostty. I'm trying to migrate from iTerm2 which has a "Show/hide all windows with a system-wide hotkey". Here is my current config:

```
command = /opt/homebrew/bin/fish
theme = Builtin Light
font-family = "Fira Code"
keybind = global:ctrl+y=toggle_visibility
```

Every time I toggle visibility, it creates a non-interactive "ghost window" behind the current window. Here, I'm toggling between iTerm and Ghostty by pressing `ctrl+y`:

https://github.com/user-attachments/assets/bb42bedd-9985-4cbc-83ef-9017b9264ce2

Separately, when visibility is hidden using this shortcut, clicking the Ghostty icon in the macOS dock does not show the Ghostty windows until triggering toggle visibility action again.

Next, pressing the toggle visibility button sometimes creates tons of empty windows:
![Image](https://github.com/user-attachments/assets/571dd371-8172-4c7c-abe3-6cb781b2f8ae)

Finally, when Ghostty gets into this state, `cmd+w` may close the session but leaves a ghost window behind:
![Image](https://github.com/user-attachments/assets/01d562ca-0de8-4b3f-8c12-58e7f0f72512)

I'm using the latest versions of everything on macOS.

**Comment by cpojer** [comment]
Oh, and I forgot, if Ghostty is open but has no windows, it would be awesome if the toggle visibility action could create a new window.

**Comment by cpojer** [comment]
cc @rolandpeelen re #2205.

**Comment by crabique** [comment]
> Oh, and I forgot, if Ghostty is open but has no windows, it would be awesome if the toggle visibility action could create a new window.

There's also incompatibility with `quit-after-last-window-closed=true`, toggling the visibility off actually exits the program entirely.

**Comment by jaysonfrancis** [comment]
fwiw, i don't experience this when toggling only the default initial window at start up.

However, if i create a new window (cmd+n), close the initial one, I experience the same thing during toggle. Also if I create tabs (cmd+t) and toggle, the tabs come back as separate windows instead of tabs


(installed via brew, Sequoia 15.3)

**Comment by ShaneK** [comment]
Looks like even just opening a new tab with cmd+t on MacOS and then toggling the visibility causes this issue. It also splits the tabs and if you do it a couple of times they'll both be broken windows showing only their title bars

**Comment by datanoise** [comment]
The last commit seems like fixes the 'ghost windows' issue, but `toggle-visibility` still splits tabs into separate windows.

**Comment by ShaneK** [comment]
Yeah, I was thinking maybe that should be made its own issue. It probably is outside the scope of this one.

**Comment by jsardev** [comment]
I found there's a discussion regarding this already here: https://github.com/ghostty-org/ghostty/discussions/4240
