### ISSUE TITLE
“Find” functionality for searching text in terminal window

### ISSUE THREAD

**Issue by r0bj** [ghostty-org/ghostty#3220]
I would like to request the addition of a “Find” feature to Ghostty that allows users to search for specific strings within the terminal window. This functionality is integral to workflow for many people and would greatly enhance the usability of Ghostty.

Use Case
As a user who frequently works with extensive terminal outputs, the ability to search for specific text strings helps in quickly locating relevant information without manually scrolling through the entire output. Many modern terminal emulators and text editors include built-in search functionalities, which are essential for handling large amounts of text. Incorporating a “Find” feature into Ghostty would make it more competitive and user-friendly.

Proposed Features
- Search Shortcut: Implement a keyboard shortcut (e.g., Command+F) to open a search input within the terminal window.
- Search Navigation: Allow users to navigate through search results using Enter and Shift+Enter or arrow keys.
- Highlight Matches: Highlight all instances of the search query within the terminal output for easy visibility.
- Case Sensitivity Option: Provide an option to toggle case-sensitive searches.
- Real-time Search: As the user types the search query, dynamically filter and highlight matching results.

**Comment by JakeWharton** [comment]
#189

**Comment by jcollie** [comment]
Please keep things professional and productive folks!
