### ISSUE TITLE
Building with --system should not force -Demit-docs

### ISSUE THREAD

**Issue by yorickpeterse** [ghostty-org/ghostty#3234]
Extracted from https://github.com/ghostty-org/ghostty/discussions/3201: when using `zig build --system`, `build.zig` forces the use of `-Demit-docs=true`, which in turn requires Pandoc. This is problematic for environments that don't have nor want to install Pandoc (e.g. because it's not available or not necessary, as is the case with Flatpaks) as it prevents building.

To resolve this, `--system` should either simply _not_ imply `-Demit-docs` _or_ you should still be able to overwrite the setting using `--system X -Demit-docs=false`.

**Comment by mitchellh** [comment]
We definitely want docs for packages by default. I think allowing it to be forced off is fine though! The reason it’s forced on now is we don’t want system packages without docs.

**Comment by BratishkaErik** [comment]
Isn't this already how it works? This path is hit only if option is not passed at all, it is certainly overridable:

https://github.com/ghostty-org/ghostty/blob/main/build.zig#L138-L147

**Comment by mitchellh** [comment]
You're correct. This can be overridden today manually. I just confirmed locally as well.
