### ISSUE TITLE
macOS: accent menu is not available

### ISSUE THREAD

**Issue by tonyjaimep** [ghostty-org/ghostty#3235]
When entering text on MacOS and a key is pressed and held, an accent menu pops up to allow the input of special characters:

![Image](https://github.com/user-attachments/assets/7d7e5de0-cf26-4b8c-9d87-74ab1eab9232)

([source](https://support.apple.com/guide/mac-help/enter-characters-with-accent-marks-on-mac-mh27474/mac))

This behavior is currently not available when typing on Ghostty:

https://github.com/user-attachments/assets/4d68a995-fc12-4239-a31f-6729221a9509

Expected:

https://github.com/user-attachments/assets/5ad83239-2c87-4e9c-9d6b-797e6d82b977

**Comment by mitchellh** [comment]
This is disabled on purpose. If you’d like to propose an alternate then open a discussion please. It’s very common to disable this in terminals.

**Comment by igorclark** [comment]
Hi there, this doesn't seem to be disabled in Ghostty v1.1.2 build 9416, the special-char box pops up on key hold. Any way to disable it? Thanks a lot!

https://github.com/user-attachments/assets/27986e0a-6650-4fe8-8969-ef9efff9426c

**Comment by 00-kat** [comment]
@igorclark I'd recommend that you create a new discussion instead of bumping this issue.
