### ISSUE TITLE
[Feature request] Layout management à la kitty

### ISSUE THREAD

**Issue by bvergnaud** [ghostty-org/ghostty#3239]
Hello,

This probably won't be high priority which is completely fine, but I'd like to open this discussion early.

One of the features of kitty I haven't really seen in other terminals is the layout system.
In kitty, I can spam the `new_split` key bind to get a certain amount of panes. And then with a single key bind, I can cycle through predefined layouts like vertical or grid.

An example of that workflow would be to open 9 shells to monitor logs on 9 different servers.
In kitty with no config at all, I would do:
* 1 system key bind to open kitty
* 1 key bind pressed 8 times to get 9 panes/splits
* 1 key bind repeated n times to cycle to the grid layout (or any other preferred layout)
(add full-screen / resize key binds to taste)

As far as I can tell from my first tests, there is a bit of that idea in the `equalize_splits` action. But I still have to be mindful of the direction in which I open my splits which require more key binds and more keypresses.

This might be specific to a certain type of workflow, but I almost never want to open arbitrary splits in my terminal anyway, that's something I would do with windows, through my tiling WM. In a terminal, I almost always use pre-determined layouts. I'm not advocating for removing arbitrary splits of course, but there is space for another type of pane management.

I'm not sure if that philosophy matches ghostty's, or if there would be a lot of demand for that feature, which is why I open this issue, so that it can be discussed.

Regardless, congrats on release 1.0, and thanks for all the hard work. Really enjoy using Ghostty so far ! 👍🏻

**Comment by mitchellh** [comment]
Thanks. This is a dupe. Please add this to the other discussion. Also issues are not for feature requests as noted in the contributing docs!
