### ISSUE TITLE
high iowait on linux

### ISSUE THREAD

**Issue by marcparadise** [ghostty-org/ghostty#3246]
I'm running ghostty 1.0 on Arch  via  the v1.0 package in the arch repo. 

Whenever I run ghostty, I see a high iowait% time reported in top (~24%) Running `iotop` does not show ghostty reading or writing, but the iowait consistently drops to zero when I terminate ghostty, and consistently returns to ~24% when I am running ghostty. 

Tried on: 

 linux 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux

And: 
linux 6.12.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000 x86_64 GNU/Linux

**Comment by gpanders** [comment]
See https://github.com/ghostty-org/ghostty/discussions/3224.
