### ISSUE TITLE
Packaging request: homebrew for Linux

### ISSUE THREAD

**Issue by etrigan63** [ghostty-org/ghostty#3247]
I am formally requesting a package for deployment via homebrew for Linux.

**Comment by gpanders** [comment]
Packaging is done by the community, not by Ghostty the project. If you want Ghostty packaged in your distribution of choice then you can volunteer to do it yourself or wait for another community member to do it.

**Comment by etrigan63** [comment]
If I knew how to do it, I would have done it.

**Comment by JakeWharton** [comment]
It was @Uzaaft
