### ISSUE TITLE
Bug when used with yabai

### ISSUE THREAD

**Issue by StepaniaH** [ghostty-org/ghostty#3254]
I'm using yabai as the window manager for macOS. When using Ghostty, window management issues occur (as shown in the image) when creating new tabs with shortcuts like Command+T or creating new windows with Command+N.

Details:
- OS Version: macOS 15.2
- Yabai Version: v7.1.5

Steps to reproduce (consistently reproducible):
1. Initially launch Ghostty
2. Create a new tab using Command+T<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/df025eb7-4c54-4f5f-a16a-f10f783ffabe" />

**Comment by mitchellh** [comment]
Use search. There's many topics covering this. Its a macOS issue.
