### ISSUE TITLE
Feature Request: add command to open new tab at the end

### ISSUE THREAD

**Issue by sionescu** [ghostty-org/ghostty#3263]
I'd like to open a new tab at the end of the tab list instead of after the current tab.

**Comment by mitchellh** [comment]
Issues aren't for feature requests or for Q&A. https://github.com/ghostty-org/ghostty/blob/main/CONTRIBUTING.md

**Comment by sionescu** [comment]
How is this completed ?

**Comment by mitchellh** [comment]
Issues aren't for feature requests.

https://github.com/ghostty-org/ghostty/blob/main/CONTRIBUTING.md
