### ISSUE TITLE
Ghossty won't launch on MacOS

### ISSUE THREAD

**Issue by joebonneau** [ghostty-org/ghostty#3272]
I've tried with both the binary provided by the homebrew cask and the .dmg provided on the website. I was able to see an application crash log when launching it at one point, but was unable to reproduce after reinstalling.

When launching via the cli (running `ghostty` in Alacritty), I get the following error:

> ghostty(12478,0x17015f000) malloc: *** error for object 0x60000054c000: pointer being freed was not allocated
ghostty(12478,0x17015f000) malloc: *** set a breakpoint in malloc_error_break to debug
fish: Job 1, 'ghostty' terminated by signal SIGABRT (Abort)

I'm on an M2 Macbook Pro. Let me know if I can provide any other details!

**Comment by mitchellh** [comment]
#3202

**Comment by joebonneau** [comment]
Ah, thank you! I don't think the note about $HOME/.cache was in that issue when I looked it a little while ago. That was indeed the issue and it's caused me grief in the past as well.
