### ISSUE TITLE
Certain paths in the docs contain spaces when the shouldn't

### ISSUE THREAD

**Issue by jorisguex** [ghostty-org/ghostty#3275]
As per the title, certain paths contain spaces when the shouldn't which make copy-and-pasting not work as expected.

Link: https://ghostty.org/docs/config/reference#theme
Screenshot: ![Image](https://github.com/user-attachments/assets/80e3f7ff-7387-42f4-a623-2136b15e7291)

**Comment by mitchellh** [comment]
These are all auto-generated by a build script so should be easy to resolve!

**Comment by mitchellh** [comment]
Fixes by #3276 thank you
