### ISSUE TITLE
macOS: `open_config` action should use `open -t`

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3284]
Excellent details in #3282

> minimally: changing open.zig to use the -t flag for this so you at least get whats configured for plain text files (e.g. associated for .txt) [also what I tried to do with defaults write after first searching "macos default editor" today] (provided open isn't being used elsewhere that is incompatible with that)

**Comment by lcrespom** [comment]
Why not use whatever is configured in the $EDITOR environment variable? Hardcore terminal users will expect ghostty config file opened in vim, not in MacOS TextEdit (ugh). In my case, I have $EDITOR set to VSCode.

MacOS lets users associate file extensions with editors, but ghostty config file has no extension, so there is no easy way to configure that at the system settings level.

**Comment by mitchellh** [comment]
The discussion discusses this. I note that’s the plan and this is a stopgap. Please read context before duplicating questions.
