### ISSUE TITLE
Extremely large mouse size on Arch Linux

### ISSUE THREAD

**Issue by TroySigX** [ghostty-org/ghostty#3286]
Here's my mouse in Ghostty:
![Image](https://github.com/user-attachments/assets/4f4a6603-674b-4e0d-b4bd-4e61e379b5e3)

And here's its size in other programs:
![Image](https://github.com/user-attachments/assets/adafdcf2-8c27-4a3b-a67d-e3efc4215f36)

**Comment by mitchellh** [comment]
Dupe. This is a GTK bug fixed in the next release. Search for more details
