### ISSUE TITLE
Failed to initialize when use Cozette font

### ISSUE THREAD

**Issue by r0nn** [ghostty-org/ghostty#3289]
Set font-famile = Cozette in config file, ghostty failed with error: "The terminal failed to initialize."

Cozette is a bitmap font: https://github.com/slavfox/Cozette, using .dfont in macOS.

OS: macOS Sequoia 15.2

**Comment by mitchellh** [comment]
Ghostty doesn’t support bitmap fonts. You can use Cozette vector. 

There’s another issue tracking not even attempting to load bitmap fonts.
