### ISSUE TITLE
Option to disable visual bell?

### ISSUE THREAD

**Issue by SinOverCos** [ghostty-org/ghostty#3305]
Here's a video of me pressing `<tab>` in vim:

https://github.com/user-attachments/assets/acc1a4ac-c555-4d4d-97f4-31672ecf4ab3

I think the iTerm 2 equivalent would be to have "visual bell" disabled: https://superuser.com/a/1680503

**Comment by mitchellh** [comment]
This is vim. Ghostty doesn’t support the bell at all yet.

**Comment by SinOverCos** [comment]
But then how come when I do the same in iTerm 2 this doesn't happen?

**Comment by mitchellh** [comment]
No idea. Try the Q&A section or discord.

**Comment by SinOverCos** [comment]
For others who come across this: vim's visual bell can be disabled with
```
set belloff=all
```

https://stackoverflow.com/a/41524053

Before I found `belloff`, I used to disable this visual flash in iTerm 2's settings, so I guess iTerm 2 has some way to deal with this. Odd that vim still flashes even when Ghostty doesn't support the bell.
