### ISSUE TITLE
Feature request: window-inherit-working-directory option to inherit working directory for the current window

### ISSUE THREAD

**Issue by spott** [ghostty-org/ghostty#3312]
I would like to be able to set an option to inherit the working directory when I create new tabs or splits within a window, but if I create a new window, it doesn't inherit the working directory (instead starting in ~).

This is sometimes nice when I'm using direnv and I screw up and break my config.  If I always inherit the working directory then I have to open a different terminal emulator to fix it.

**Comment by mitchellh** [comment]
Dupe! Search please it’s one of the oldest issues

**Comment by JakeWharton** [comment]
#1392
