### ISSUE TITLE
Window display corrupts after display change

### ISSUE THREAD

**Issue by skaragianis** [ghostty-org/ghostty#3313]
When closing the lid of my laptop, when on battery, and immediately connecting power and monitor, the terminal window that appears has become garbled. Switching tabs cleared up the second. The first cleared up after a small window resize.

![Image](https://github.com/user-attachments/assets/010bb242-0c5d-4e6d-9e94-2cf8620b1861)

Apple MacBook Air M3 running Sonoma 14.3. And yes I've gone back to '22 to finish an AOC I never did 😉

**Comment by mitchellh** [comment]
This is a dupe! Search quick terminal. Still trying to chase down the cause.
