### ISSUE TITLE
ctrl+shift+d pastes "100;6u" into micro editor

### ISSUE THREAD

**Issue by qwelias** [ghostty-org/ghostty#3314]
I'm using micro editor: https://github.com/zyedidia/micro

And on `ctrl+shift+d` it should dupe the line, but instead with ghostty it pastes `100;6u`.
I did try to add `keybind = ctrl+shift+d=unbind` to config, but it did not do anything.

It works as expected with Gnome Terminal.

**Comment by 00-kat** [comment]
`ctrl+d` duplicates a line in micro, not `ctrl+shift+d`; I didn't try Gnome Terminal, but Foot seems to send `ctrl+d` when you press `ctrl+shift+d`, which is why it works there.

**Comment by qwelias** [comment]
@00-kat you're right, I just used to `ctrl+shift+d` to work the same
