### ISSUE TITLE
font-size config not working

### ISSUE THREAD

**Issue by vipulbhj** [ghostty-org/ghostty#3315]
I am using Mac OS 15.1 and when I tried changing the font-size, it doesn't work for some reason. Am I doing something wrong ?

When I run `ghostty +show-config`, I can see it's reading the `font-size` correctly from the config, but not applying it for some reason.

```console
> ghostty +show-config
font-size = 100
command = /bin/zsh
click-repeat-interval = 500
auto-update-channel = stable
```

The config file is at `~/.config/ghostty/config`, and has 

```console
font-size = 100
```

Btw, I also tried 24, 36 and a bunch of other values too, but non seem to work and when I try to reload with `cmd-shift-+`, I just see the enter key being inserted and the reload doesn't work.

**Comment by mouyase** [comment]
change font size need restart app

**Comment by jcollie** [comment]
The `font-size` setting sets the default for new surfaces. Reloading the config after changing the setting does not change the font size of existing surfaces. You can hit `ctrl+0` to change the font size to the new default in existing windows.

**Comment by vipulbhj** [comment]
Okay thanks, I see what's up.

Does `cmd-shift-+` work ? As described in docs ?

**Comment by AnirudhG07** [comment]
for me `cmd shift -` works but not `+`
