### ISSUE TITLE
Rectangular text selection

### ISSUE THREAD

**Issue by qwelias** [ghostty-org/ghostty#3319]
Gnome Terminal allows to select a rectangular screen text area with mouse cursor while holding `ctrl`.

Is it possible to support the same feature in ghostty?

**Comment by jcollie** [comment]
Hold down `ctrl` and `alt`.

**Comment by daniellandau** [comment]
Is it possible to change that keybinding?

**Comment by ericaltendorf** [comment]
+1, i have alt+click bound to window move/resize

**Comment by 00-kat** [comment]
#3848.
