### ISSUE TITLE
`background-opacity` does not function properly

### ISSUE THREAD

**Issue by lixiaoyan** [ghostty-org/ghostty#3324]
Minimal reproducible config:
```
theme = catppuccin-latte
background-opacity = 0.2
```

It's especially obvious with light themes:
<img width="552" alt="Image" src="https://github.com/user-attachments/assets/a91d79df-c5c5-4857-83e2-95d52faf1e1d" />

Dark themes perform better, but the color is still not accurate:
<img width="515" alt="Image" src="https://github.com/user-attachments/assets/03ce53a1-c5f8-4f86-9642-07433492a5ec" />

The bug is related to color blending, or more specifically, the incorrect usage of premultiplied alpha.

**Comment by lixiaoyan** [comment]
I guess it might be related to premultiplied alpha, although I haven't read the code.

**Comment by lixiaoyan** [comment]
<img width="999" alt="Image" src="https://github.com/user-attachments/assets/0dd1bbef-23ee-4fa1-ac99-43bc1d11170c" />
Confirmed. Premultiplying alpha resolves this issue.
<img width="506" alt="Image" src="https://github.com/user-attachments/assets/007b7a29-61c2-4c3e-a8e2-874100ec2bc1" />

**Comment by SimonYde** [comment]
as seen in #3449, this is not just a macos issue, it is based on theme alone.

**Comment by lixiaoyan** [comment]
@SimonYde I think #3347 can resolve the problem on Linux as well. If it's convenient for you, could you help me test this fix on Linux?

**Comment by sethgrid** [comment]
I just brew installed ghostty. I set the theme in an included config file. in the base config file I put background-opacity = 95, and it only affects the title bar of the window. The actual window contents stay 100% opacity

**Comment by rplnt** [comment]
@sethgrid Have you tried restart (of Ghostty)? For me the reload config does not work as reliably when it comes to opacity. Had the title bar thing as well, but I think restart instead of reload helped.

**Comment by injust** [comment]
> background-opacity = 95

@sethgrid Do you literally have `background-opacity = 95` in your config? You probably want `0.95` instead.

**Comment by latin-1** [comment]
@injust I believe that changing the background-opacity from 1 (opaque/default) to any value lower than 1 requires a restart, at least on macOS.

**Comment by SimonYde** [comment]
> [@injust](https://github.com/injust) I believe that changing the background-opacity from 1 (opaque/default) to any value lower than 1 requires a restart, at least on macOS.

turns out it is the same on Linux, so restarting fixed it for my theme. However, I can reproduce the bug with `catppuccin-mocha` as my theme

**Comment by raylee** [comment]
@lixiaoyan Thanks for tracking this down. I was just noticing that setting an alpha could make my Ghostty window brighter than either the background theme or my wallpaper, so I was thinking it was a blend mode bug.

Reviewing your PR, I'm wondering if you should be premultiplying by (1-alpha) for the background:

`alpha * fg + (1-alpha) * bg` = resulting color, no?

**Comment by lixiaoyan** [comment]
@raylee Nope, that's not how "premultiplied alpha" works. We only need to premultiply alpha for the foreground (the **background** of terminal), and the shader will handle the rest.
See: https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied

**Comment by sethgrid** [comment]
> I just brew installed ghostty. I set the theme in an included config file. in the base config file I put background-opacity = 95, and it only affects the title bar of the window. The actual window contents stay 100% opacity

per other's recommendations, restarting worked. Opacity working as expected. And, yeah, typo: that is 0.95; updated to 0.6

**Comment by angelplusultra** [comment]
It works if you do a hard restart of Ghostty like @rplnt said.

**Comment by yspreen** [comment]
I'm running @lixiaoyan 's fork on my machine now, works very well. merging #3347 seems like a win to me

**Comment by gko** [comment]
in my case the following config didn't work even after a hard restart:
```
background-opacity = 0.7
background = #fafafa
```

**Comment by ignamartinoli** [comment]
@gko same thing on Hyprland with `background-opacity = 0.8` and version `ghostty-1.0.1`.

**Comment by 1Jo1** [comment]
same issue on Niri with `background-opacity = 0.6` and ghostty version `1.2.3-arch2`

**Comment by pluiedev** [comment]
Please create a new Issue Triage discussion instead of commenting on old, closed issues.
