### ISSUE TITLE
Ctrl-g on macOS emits ^[, rather than ^G

### ISSUE THREAD

**Issue by aaronjensen** [ghostty-org/ghostty#3330]
I have tried this with Zsh, Bash, and Emacs, all report the same.

### ghostty

The first keypress below is `C-g`, which should be `^G` and `\a`, but is instead `^[`. The second is `C-i`, just demonstrating that fixterm/extended keys are functioning.

![Image](https://github.com/user-attachments/assets/9ef6a42e-6aee-4e94-a2d6-89c5412b54bb)

### iTerm2

![Image](https://github.com/user-attachments/assets/72af8c7f-afd5-4a4b-bdf9-be1e85f66859)

**Comment by gpanders** [comment]
I'm not able to reproduce this.

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/3523a311-009a-441c-b0cf-94318d34553d" />

**Comment by aaronjensen** [comment]
Ah! This is my fault. I'm sorry for the noise. In my case, I have a Hammerspoon script that does readline key translations for apps other than specific ones I have listed. I needed to add ghostty.
