### ISSUE TITLE
[Bug] Cannot run from the launcher in Gnome Fedora

### ISSUE THREAD

**Issue by RomanAverin** [ghostty-org/ghostty#3333]
After installation according to the instructions. 
Gnome launcher does not detect Ghostty.
The path to ~/.local/bin is in PATH.
Rebooting didn't help either. There's also no ghostty icon.

![Image](https://github.com/user-attachments/assets/2478fea4-e288-4e49-86c6-0834d2d12c5b)

**Comment by sedax90** [comment]
same problem with Ubuntu 22.04 (Gnome)

**Comment by pandalec** [comment]
I use 'ghostty-git' from AUR on arch and it works. Placed icon into GNOME's dock

**Comment by 4193883-eng** [comment]
fedora 41 same

**Comment by mgolvers** [comment]
Had the same issue on Fedora 41. 
Used this command to build ghostty:  zig build -p $HOME/.local -Doptimize=ReleaseFast

In my case it helped to modify Exec lines in this file ~/.local/share/applications/com.mitchellh.ghostty.desktop 
I set the Exec value to full path, like this:

Exec=/home/username/.local/bin/ghostty

**Comment by Angxddeep** [comment]
didn't occur in fedora KDE so it's a gnome specific issue

**Comment by sudomateo** [comment]
Others have already mentioned this but here's the direct link to the documentation that describes using the `-p` flag to fix missing icons: https://ghostty.org/docs/install/build#installation-directory

> Use `zig build` with the `-p` (prefix) flag to install Ghostty into a target directory. This will setup the proper FHS directory structure that ensures features such as shell integration, icons, GTK shortcuts, etc. all work.
>
> For local, unprivileged installs, we recommend `$HOME/.local`:
>
> ```
> zig build -p $HOME/.local -Doptimize=ReleaseFast
> ```

**Comment by king-11** [comment]
>In my case it helped to modify Exec lines in this file ~/.local/share/applications/com.mitchellh.ghostty.desktop I set the Exec value to full path, like this:
>
>Exec=/home/username/.local/bin/ghostty

This helped

**Comment by paolomissagia** [comment]
I see that the issue has been closed, but I think adding a bit of more context here can be helpful to others. Keep in mind I haven’t spent much time on it to troubleshoot the reason for the problem. 

First, it is not exclusively to Fedora as it is affecting people on Ubuntu too (when using Gnome). It is also not related to missing icons as the .desktop files are created. The issue on mine experience is that these files are not being picked up by the app launcher. 

As mentioned above, updating the exec command from “ghostty” to the full path executable makes these files visible. 

Hopefully that helps new users that are building it from source.

**Comment by sudomateo** [comment]
> As mentioned above, updating the exec command from “ghostty” to the full path executable makes these files visible.
> 
> Hopefully that helps new users that are building it from source.

Alternatively, one could ensure `~/.local/bin` is on `PATH` so no modifications to `Exec` are necessary. I edited https://github.com/ghostty-org/ghostty/issues/3333#issuecomment-2563884474 with more details.

**Comment by paolomissagia** [comment]
> > As mentioned above, updating the exec command from “ghostty” to the full path executable makes these files visible.
> > Hopefully that helps new users that are building it from source.
> 
> Alternatively, one could ensure `~/.local/bin` is on `PATH` so no modifications to `Exec` are necessary. I edited [#3333 (comment)](https://github.com/ghostty-org/ghostty/issues/3333#issuecomment-2563884474) with more details.

Thanks for the comment @sudomateo. 

I forgot to mentioned that I have updated my PATH and I can launch ghostty via the terminal without issues. I haven't seem many more people raising this issue so it could be something specific to my setup - I will have a look tomorrow when I have some free time and come back here if there is any new relevant information.

**Comment by mgolvers** [comment]
> Had the same issue on Fedora 41. Used this command to build ghostty: zig build -p $HOME/.local -Doptimize=ReleaseFast
> 
> In my case it helped to modify Exec lines in this file ~/.local/share/applications/com.mitchellh.ghostty.desktop I set the Exec value to full path, like this:
> 
> Exec=/home/username/.local/bin/ghostty

Just to add a little more info, in my case ~/.local/bin was already in PATH and I could launch it via a different teminal using only ghostty command, just as mentioned above.  But still it wasn't not discovered by the app launcher.

**Comment by king-11** [comment]
Issue was the same for as well the PATH was set properly on fedora.

**Comment by sudomateo** [comment]
Ah, I see what the issue is. `Exec` uses your user's default shell to run the specified program. Unsure if that's a login shell or not but it doesn't matter in my use case.

I use `fish` in my terminal but my user's default shell is still `/bin/bash`.

```
> getent passwd (whoami) | cut -d ':' -f 7
/bin/bash
```

And I have the following in my `~/.bashrc`.

```
# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
```

That's why I never had to touch `~/.local/share/applications/com.mitchellh.ghostty.desktop` on my installations. If you're one that cares about not modifying default files then just ensure `ghostty` is on your default shell's `PATH`.

**Comment by mgolvers** [comment]
I was just curious :D

Tried to install a blank (Fedora 41 Gnome DE) didn't modify anything, just installed the required tools and build from source. 

The app launcher found ghostty immediately.

--- 

Then installed one more instance:  
    - updated it, 
    - updated zshrc with additional PATH, 
    - set my users default shell to zsh (same as i am using on my original system).
    - rebooted the instance 
    - build from source ghostty

The app launcher could not find ghostty. 

Changed the default shell to bash and app launcher found it.

Set it back to zsh and app launcher didn't find it.

zsh: 
![Image](https://github.com/user-attachments/assets/4138f364-d41c-4fbd-bb84-92cbcbf94472)

bash: 
![Image](https://github.com/user-attachments/assets/93832b3c-e636-4fb2-93c2-f5f48c4571f2)


It looks like it matters which shell do you use.

**Comment by BridgeSenseDev** [comment]
I was facing the same issue on Fedora 41 (KDE), when my shell was set to zsh. I was able to fix it by creating `~/.zprofile` and adding this line to it:
```zsh
PATH=$HOME/.local/bin:$HOME/bin:$PATH
```
It was already in `~/.zshrc` but it wasnt enough

**Comment by bittner** [comment]
Today, the problem apparently is the `DBusActivatable=true` value in Ghostty's desktop file. See https://github.com/ghostty-org/ghostty/discussions/10617 for details.
