### ISSUE TITLE
[BUG 🐞] Double and random letters when typing on a SSH MacOS -> Ubuntu connection

### ISSUE THREAD

**Issue by jquintanilla4** [ghostty-org/ghostty#3335]
When i try to SSH on my local network from MacOS 15.2 to Ubuntu 24.04, it starts to double type letters or type random letters. I know it's a ghostty issue, because I've never had the issue with Warp or MacOS Terminal. I've tried to replicate the bug on both those emulators and had no issues. I've restarted both computers multiple times to try to see if that would fix the issue, nope.

The only additions i've made to the ghostty config is to change the background color and window size.

Seems like a weird bug. Let me know if you need more information.

**Comment by weareDMNTRs** [comment]
Same issues here. When connecting via SSH to Ubuntu, strange things happen…

**Comment by punoko** [comment]
Same issues with Arch Linux targets as reported here https://github.com/ghostty-org/ghostty/issues/3338

**Comment by jquintanilla4** [comment]
> Same issues with Arch Linux targets as reported here [#3338](https://github.com/ghostty-org/ghostty/issues/3338)

I do have zsh-autosuggestions installed on both MacOS and Ubuntu. So yeah, might be tied to that.

**Comment by anund** [comment]
What's the value of `$TERM` before you ssh? You're likely running into:https://ghostty.org/docs/help/terminfo#ssh.

Your remote likely doesn't have a terminfo entry for ghostty. Watch https://github.com/ghostty-org/ghostty/issues/2542 longer term. This should be a discussion. issues are actionable, discussions are for help or debugging.

**Comment by nickkadutskyi** [comment]
It sounds like some issue with terming.
Try `TERM=xterm-256color ; ssh ...`
If that helps you can set it permanently for all of your ssh connections like this:
```
Host *
  SetEnv TERM=xterm-256color
```

**Comment by jquintanilla4** [comment]
> What's the value of `$TERM` before you ssh? You're likely running into:https://ghostty.org/docs/help/terminfo#ssh.
> 
> Your remote likely doesn't have a terminfo entry for ghostty. Watch [#2542](https://github.com/ghostty-org/ghostty/issues/2542) longer term. This should be a discussion. issues are actionable, discussions are for help or debugging.

xterm-ghostty

And yes, just tested the info on the documentation. It worked.

**Comment by jquintanilla4** [comment]
Issue solved.

**Comment by aindriu80** [comment]
Same issue, thanks for the solution. Added the following to ~/.zshrc

`export TERM=xterm-256color`

**Comment by AisyIE** [comment]
> Same issue, thanks for the solution. Added the following to ~/.zshrc
> 
> `export TERM=xterm-256color`

I have the question in my archlinux, no ssh. After using the command, it works :).

**Comment by donatj** [comment]
Like we have a workaround here... but I feel like this should be reopened. We shouldn't have to use a workaround.

**Comment by jcollie** [comment]
> Like we have a workaround here... but I feel like this should be reopened. We shouldn't have to use a workaround.

The solution is getting the Ghostty terminfo installed everywhere. You don't see this problem with other terminal emulators because they have been around long enough for their terminfo to be integrated into distributions. But if you connect to a system that's old enough,or just has a very minimal set of terminfos installed you can have this problem with any terminal emulator.

**Comment by akoblentz** [comment]
Thank you! This was driving me nuts.
