### ISSUE TITLE
class cannot be changed

### ISSUE THREAD

**Issue by samtrek** [ghostty-org/ghostty#3336]
The class of the app cannot be changed to another name

## To reproduce
1. change class under the config as `class="ghostty"` or another class name
2. close all existing instance
3. launch app
4. check app class through windows manager provided tools

## Result
The app class is always returned as `com.mitchellh.ghostty`

## Expected result
The app class should be changed to the new class given in the config or at the terminal

## Details
OS: Arch linux: 6.6.67-1-lts,
Window manager: hyprland: 0.46.2
ghossty version: Ghostty 1.0.0-dev+0000000

## Config
font-size = 10
theme = light:tokyonight-day,dark:tokyonight-storm
command = /bin/zsh
class = ghostty
window-decoration = false
window-theme = system
click-repeat-interval = 500
gtk-single-instance = true
gtk-tabs-location = bottom
auto-update-channel = tip

**Comment by Stewart86** [comment]
you need to follow [GTK requirements](https://docs.gtk.org/gio/type_func.Application.id_is_valid.html). try `class=my.ghostty`

**Comment by samtrek** [comment]
> you need to follow [GTK requirements](https://docs.gtk.org/gio/type_func.Application.id_is_valid.html). try `class=my.ghostty`

Thank you

**Comment by MartinCura** [comment]
Just in case someone makes the same dumb mistake as me, i was not passing the arg correctly:
```bash
# didn't work
ghostty --class com.mitchellh.ghostty-floating
# does work
ghostty --class=com.mitchellh.ghostty-floating
```
