### ISSUE TITLE
Quick Terminal - no 'focus-follows-mouse' functionality

### ISSUE THREAD

**Issue by edrozenberg** [ghostty-org/ghostty#3337]
Ghostty Version 1.0.0
Build 8469
Commit 4b4d4062

(MacOS)

I noticed when using splits in the Quick Terminal, `focus-follows-mouse = true` does not have an effect in the Quick Terminal. This may be working as intended though, and having focus follow inside splits inside the Quick Terminal is a pretty niche use case tbh.

**Comment by mitchellh** [comment]
This should work. Marked as bug.
