### ISSUE TITLE
How to remap `⌥`  and `⌘`?

### ISSUE THREAD

**Issue by zen-xu** [ghostty-org/ghostty#3342]
iTerm supports to remap `option` and `command` key

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/19b133e6-75b8-47d3-a78c-568c5494d22c" />

**Comment by ThatSealgair** [comment]
This is the documentation on [keybindings](https://ghostty.org/docs/config/keybind).
I hope this help.

**Comment by mitchellh** [comment]
#3493
