### ISSUE TITLE
Usability Issue in SSH

### ISSUE THREAD

**Issue by jayanthchandra** [ghostty-org/ghostty#3348]
Hello,

Congrats on the launch, the terminal definitely feels faster compared to my wez setup

These are the issue which i encountered while testing out with ssh. 
OS: Mac Sonama 14.7

1> Ctrl + L (Clean Screen) doesnt work. 
![Image](https://github.com/user-attachments/assets/8e780a4e-6cda-4b3c-a8bb-54a36fb77d87)

2> Clear command doesn't work. 
<img width="734" alt="Image" src="https://github.com/user-attachments/assets/50bf4d88-ac3b-49a6-878a-604067df659c" />

3> Backspace/Delete doesnt work. 
https://github.com/user-attachments/assets/de064fde-65f0-4a61-8f2b-8b9d20151d93

**Comment by r32pat** [comment]
I got around this by setting the following in my config.

term = xterm-256color

There are a lot of options you can set this to so your milage may vary.
But give that a shot, close and restart Ghostty and see how you go.

**Comment by aarondjudzman** [comment]
Solution here: https://ghostty.org/docs/help/terminfo#ssh

**Comment by r32pat** [comment]
The solution @aarondjudzman is much better than my suggestion and I'll probably change my setup to follow that guidance.

**Comment by jayanthchandra** [comment]
Thanks @aarondjudzman. This fixes the issue.
