### ISSUE TITLE
Config format: Allow same-line comments

### ISSUE THREAD

**Issue by eugenesvk** [ghostty-org/ghostty#3350]
`cursor-style=block #block bar underline block_hollow` sets a style and reminds future user what the available options are without the need to consult an external reference or wasting vertical space

**Comment by mitchellh** [comment]
Rejected. This has been discussed before so please find that issue for more details on why. 😄

**Comment by eugenesvk** [comment]
Sorry I missed the dupe, commented there
https://github.com/ghostty-org/ghostty/issues/1247
