### ISSUE TITLE
[macOS]: Application doesn't restore window size nor placement between restarts

### ISSUE THREAD

**Issue by feketegy** [ghostty-org/ghostty#3356]
This could either be a bug or a feature tbh.

Open the application, resize the window, close the application (CMD+Q) then re-open it again. The window size nor the window placement is restored on screen.

**Comment by bnjmnt4n** [comment]
See https://ghostty.org/docs/config/reference#window-save-state.

**Comment by feketegy** [comment]
Sorry I should've looked at the configs more carefully
