### ISSUE TITLE
Say no to CSD

### ISSUE THREAD

**Issue by bangbangsheshotmedown** [ghostty-org/ghostty#3371]
my desktop is not an iPad, and i don't have a "touch screen", i don't want to "touch" UI elements

![Image](https://github.com/user-attachments/assets/226dd8d2-6d65-4c0b-ad0b-ae497705021f)

![Image](https://github.com/user-attachments/assets/ba213417-363e-4b3a-8fc5-ea724aaea8df)

**Comment by jwijenbergh** [comment]
just disable them https://ghostty.org/docs/config/reference#window-decoration

**Comment by bangbangsheshotmedown** [comment]
i am not talking about window decoration i am talking about CSD

I feel it's gonna get hard to stay polite

Let's play a "Find the Difference" game, accessible to everyone starting from 3 yo

Everyone, take another look a both screenshots and find the difference

If you have limited brain capabilities and need help, take a look at this: https://wiki.gnome.org/Initiatives(2f)CSD.html

CSD is a gnome thing, unix is not gnome

if you want to be portable, you don't follow gnome's stupidity, you stay sane and you do what everyone else does, you respect the window manager

**Comment by rockorager** [comment]
@bangbangsheshotmedown There is no reason to be rude like this. Window decorations are an opinion. You disagree with it, and there is no reason to belittle anyone about it.

**Comment by j7nw4r** [comment]
This is not a constructive issue. I would suggest the owners close this.

**Comment by mitchellh** [comment]
Your tone is unacceptable. Please consider approaching issues and feedback with kindness or simply use another terminal. Goodbye! 👋

**Comment by dodwyer** [comment]
Truly, thank you for providing a pitch perfect GitHub Issue example. 

This really helps set the bar for new contributors, many of whom are concerned about making community-facing mistakes when engaging in their first OSS contributions. From now on, I can simply send them this link and say, "No matter how bad you think you'll be, you'll never beat this."
