### ISSUE TITLE
ghostty +list-themes stopped working on Sonoma 14.7

### ISSUE THREAD

**Issue by habahabahaba** [ghostty-org/ghostty#3378]
After running `ghostty +list-themes` inside Ghostty or other terminal, I get a blank screen with a blinking cursor without any ability to `ctrl-c`.  Window title shows "Ghostty Theme Preview" between two ghost emotes.
Disabling (renaming) the config doesn't help.
Reinstalling Ghostty (with brew) didn't help.

**Comment by westerlind** [comment]
Same issue for me on macOS Sequoia 15.2

It worked perfectly initially, but after playing around with Ghostty a bit, and setting a theme among other things, it stopped working and behaves exactly as described.

I tried to remove all configuration and a custom theme I added to ~/.config/ghostty/themes to see if it would make a difference, but I have not been able to make it work again no matter what I do.

**Comment by rockorager** [comment]
What is the size of your terminal when launching the command? Also, you are for sure running this inside Ghostty?

**Comment by habahabahaba** [comment]
> What is the size of your terminal when launching the command? Also, you are for sure running this inside Ghostty?

1. Tried with `93x54` and `183x50` with the same result.
2. I am sure.

**Comment by rockorager** [comment]
Could you open up the inspector while trying to run ghostty +list-tehemes and
send a screenshot of the left side of the modes tab? Should generically look
like:

[ ] 2 disable_keyboard
[ ] 4 insert
...

**Comment by habahabahaba** [comment]
Here you go:
![Image](https://github.com/user-attachments/assets/de1f97c1-e9f3-4f4c-a91b-8e5ab224881a)
![Image](https://github.com/user-attachments/assets/eb286eed-5601-43f2-af92-f161c77e3a90)
![Image](https://github.com/user-attachments/assets/4e42189b-3d85-40ba-93c6-6ec250e947b2)

**Comment by rockorager** [comment]
The question mark was outside of the command haha.


`ghostty +list-themes | cat -`

**Comment by rockorager** [comment]
> BTW, does Ghostty modify `.zshrc` ?

Not directly. It has automatic shell integration for zsh which it handles on it's own, but it's not touching your .zshrc

**Comment by habahabahaba** [comment]
> The question mark was outside of the command haha.
> 
> `ghostty +list-themes | cat -`

I get a list of themes (too large to paste here).

**Comment by habahabahaba** [comment]
Also, the list starts with `.DS_Store (user)`.

**Comment by rockorager** [comment]
> Also, the list starts with `.DS_Store (user)`.

Oh that's interesting...let me look at some code to see if that is causing a silent parse error in the TUI.

**Comment by westerlind** [comment]
> Also, the list starts with `.DS_Store (user)`.

Good find!
I had .DS_Store there too, and when I removed it the problem went away, and it works like expected again now!

**Comment by westerlind** [comment]
macOS will put .DS_Store in folders that are used with Finder (I don't know the exact pattern, as it doesn't always do it, but it does sometimes anyway), so it would probably be a good idea to make Ghostty ignore that specific file.

**Comment by rockorager** [comment]
Yep, I'm putting together a patch now.

**Comment by habahabahaba** [comment]
> Yep, I'm putting together a patch now.

Thank you, [rockorager](https://github.com/rockorager)!
