### ISSUE TITLE
Round rendered terminal output so corners look good when not maximized

### ISSUE THREAD

**Issue by ansipunk** [ghostty-org/ghostty#3383]
As you can see here, it doesn't look as good as it could.

![Image](https://github.com/user-attachments/assets/ed8e3c39-b310-47da-bf56-ca041cb7b40a)
![Image](https://github.com/user-attachments/assets/baf04fbf-7d37-41d8-afea-fca9e7c69fda)

**Comment by ansipunk** [comment]
It also looks a bit weird when I set padding to 0:

![Image](https://github.com/user-attachments/assets/6960a5b9-b618-4f5c-a592-44a71083ceda)

**Comment by mitchellh** [comment]
We don't render these, the OS does.
