### ISSUE TITLE
Fails on start on macOS Sequoia 15.2

### ISSUE THREAD

**Issue by crjaensch** [ghostty-org/ghostty#3390]
I downloaded the universal binary (as .dmg) and installed it on my M2 Macbook laptop running macOS 15.2.

Below is the error report when I open the app.
---
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               ghostty [74363]
Path:                  /Applications/Ghostty.app/Contents/MacOS/ghostty
Identifier:            com.mitchellh.ghostty
Version:               1.0.0 (8469)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-12-27 13:42:23.4462 +0100
OS Version:            macOS 15.2 (24C101)
Report Version:        12
Anonymous UUID:        70D49537-B82C-FC85-038F-292464B7FC61

Sleep/Wake UUID:       EBB10757-84F1-498F-ACBF-73D3E0BC02B7

Time Awake Since Boot: 150000 seconds
Time Since Wake:       824 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   ghostty [74363]

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   ghostty                       	       0x10453564c std::__1::unordered_map<char const*, int, (anonymous namespace)::str_hash, (anonymous namespace)::str_eq, std::__1::allocator<std::__1::pair<char const* const, int>>>::operator[](char const*&&) + 244
1   ghostty                       	       0x104439e70 AppDelegate.init() + 652
2   ghostty                       	       0x104439fe0 @objc AppDelegate.init() + 20
3   AppKit                        	       0x194cee8a0 -[NSClassSwapper initWithCoder:] + 744
4   UIFoundation                  	       0x196109afc UINibDecoderDecodeObjectForValue + 684
5   UIFoundation                  	       0x196109838 -[UINibDecoder decodeObjectForKey:] + 308
6   AppKit                        	       0x194c7d8fc -[NSNibConnector initWithCoder:] + 88
7   AppKit                        	       0x194c7d7b4 -[NSNibOutletConnector initWithCoder:] + 172
8   UIFoundation                  	       0x196109afc UINibDecoderDecodeObjectForValue + 684
9   UIFoundation                  	       0x196109c88 UINibDecoderDecodeObjectForValue + 1080
10  UIFoundation                  	       0x196109838 -[UINibDecoder decodeObjectForKey:] + 308
11  AppKit                        	       0x194c7c8f4 -[NSIBObjectData initWithCoder:] + 136
12  UIFoundation                  	       0x196109afc UINibDecoderDecodeObjectForValue + 684
13  UIFoundation                  	       0x196109838 -[UINibDecoder decodeObjectForKey:] + 308
14  AppKit                        	       0x194c7c70c loadNib + 264
15  AppKit                        	       0x194c7bd80 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 560
16  AppKit                        	       0x194c7ba84 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 180
17  AppKit                        	       0x194c7b8a8 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 300
18  AppKit                        	       0x194c6e6cc NSApplicationMain + 496
19  ghostty                       	       0x10440d990 main + 312
20  dyld                          	       0x190cd4274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x19104f0e8 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19104f0e8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19104f0e8 start_wqthread + 0

Thread 4 Crashed:
0   libsystem_kernel.dylib        	       0x19101b720 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x191053f70 pthread_kill + 288
2   libsystem_c.dylib             	       0x190f60908 abort + 128
3   libsystem_malloc.dylib        	       0x190e69ea0 malloc_vreport + 896
4   libsystem_malloc.dylib        	       0x190e6da24 malloc_report + 64
5   libsystem_malloc.dylib        	       0x190e8c184 find_zone_and_free + 528
6   ghostty                       	       0x104758dcc Thread.PosixThreadImpl.spawn__anon_26771.Instance.entryFn + 284
7   libsystem_pthread.dylib       	       0x19104f0fc thread_start + 8

Thread 4 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000073   x5: 0x000000000000002e   x6: 0x0000000000000001   x7: 0x0000000000000000
    x8: 0x0452e363c075abf1   x9: 0x0452e362accf9bf1  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000037  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x0000000202f66cb0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000007c0f  x21: 0x000000016cba30e0  x22: 0x0000000190e99377  x23: 0x000000016cba2ec0
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x000000016b9f7c71  x27: 0x000000016cba3000
   x28: 0x0000000000000000   fp: 0x000000016cba2810   lr: 0x0000000191053f70
    sp: 0x000000016cba27f0   pc: 0x000000019101b720 cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x104408000 -        0x1053b7fff com.mitchellh.ghostty (1.0.0) <5fa411d7-5e7e-3ea2-8945-aaf65e6fafc0> /Applications/Ghostty.app/Contents/MacOS/ghostty
       0x10580c000 -        0x10584ffff org.sparkle-project.Sparkle (2.6.3) <914decbd-a6a8-366a-99ff-0316837f8814> /Applications/Ghostty.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x194c6a000 -        0x1960a2fff com.apple.AppKit (6.9) <4251ee1c-062c-3b9a-b6e2-751f77ef9f4a> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1960a3000 -        0x196254fff com.apple.UIFoundation (1.0) <1edae02d-93d0-3cad-80e6-55c2cd9c09ba> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
       0x190cce000 -        0x190d4ff3f dyld (*) <4ce86d18-f3fa-3d2a-a1b8-e7cd8a52fb0d> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19104d000 -        0x191059fff libsystem_pthread.dylib (*) <f1661613-b1c8-320d-b69d-97f174130e29> /usr/lib/system/libsystem_pthread.dylib
       0x191012000 -        0x19104cff7 libsystem_kernel.dylib (*) <dfc9530c-e75b-3d1c-a9a6-85c8a709d6a7> /usr/lib/system/libsystem_kernel.dylib
       0x190ee7000 -        0x190f68ffb libsystem_c.dylib (*) <67989e50-e562-3062-9ff9-44bd90648e66> /usr/lib/system/libsystem_c.dylib
       0x190e5b000 -        0x190e9cff7 libsystem_malloc.dylib (*) <d2681e0d-7831-3d34-b6bc-ce8723de184b> /usr/lib/system/libsystem_malloc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=869.9M written=498K(0%) resident=498K(0%) swapped_out=0K(0%) unallocated=869.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          448K       23 
CoreGraphics                        16K        1 
CoreServices                        32K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           843.4M       40 
MALLOC guard page                  288K       18 
STACK GUARD                       56.1M        5 
Stack                             25.6M        5 
VM_ALLOCATE                         48K        3 
__AUTH                            1992K      282 
__AUTH_CONST                      30.3M      460 
__CTF                               824        1 
__DATA                            10.1M      441 
__DATA_CONST                      15.2M      466 
__DATA_DIRTY                      1029K      140 
__FONT_DATA                        2352        1 
__LINKEDIT                       609.2M        3 
__OBJC_RW                         2373K        1 
__TEXT                           567.9M      483 
__TPRO_CONST                       272K        2 
mapped file                       59.1M       10 
owned unmapped memory               32K        1 
page table in kernel               498K        1 
shared memory                      864K       13 
===========                     =======  ======= 
TOTAL                              2.2G     2403

**Comment by mitchellh** [comment]
#3202

**Comment by crjaensch** [comment]
Thanks for the quick response!
I had forgotten that I externalized $HOME/.cache via a soft link to an external disk because some of my apps (such as gpt4all and lm-studio) store huge local LLMs in that directory.
Once I connected the external 2 TB disk to my laptop, Ghostty worked just fine :-)

**Comment by crjaensch** [comment]
@mitchellh Maybe a short note about the use of $HOME/.cache in the installation guides would help others:
As far as I am concerned the issue can be closed. Thanks!
