### ISSUE TITLE
cursor-style = block does not work for macOS

### ISSUE THREAD

**Issue by successgo** [ghostty-org/ghostty#3402]
It shows the default vertical line.

**Comment by JahsehJ** [comment]
Hello! Make sure to check the note below: https://ghostty.org/docs/config/reference#cursor-style

> Note that shell integration will automatically set the cursor to a bar at a prompt, regardless of this configuration. You can disable that behavior by specifying shell-integration-features = no-cursor or disabling shell integration entirely.

**Comment by gpanders** [comment]
Shell integration overrides the cursor-style option. Please refer to https://ghostty.org/docs/config/reference#cursor-style

**Comment by successgo** [comment]
Thank you guys, now it works.

**Comment by charlesgardyn** [comment]
@dacheng-gao what did you do? `shell-integration-features = no-cursor` didn't work for me

**Comment by 00-kat** [comment]
That should have worked, [open a new discussion] instead of bumping this ancient one please!

[open a new discussion]: https://github.com/ghostty-org/ghostty/discussions/new?category=issue-triage
