### ISSUE TITLE
`goto_split` works differently depending on the order in which splits are created

### ISSUE THREAD

**Issue by eysi09** [ghostty-org/ghostty#3408]
First off, just wanted to thank you for this awesome project and congratulations on the launch! It's been really exciting watching the development and I'm very happy to be finally able to try it. 

## Issue

Navigating between splits with the `goto:split` action doesn't work consistently depending on the order in which the splits are created. So this issue kind of has several permutations but below are some concrete examples of this.

## Repro 1

First split the window into four panes like so: 

```console
┌───┬───┐
│ A │ B │
├───┼───┤
│ C │ D │
└───┴───┘
```

...with the following actions:

1. In pane `A` use `new_split:right` to create `B`
2. In pane `A` use `new_split:down` to create `C`
3. In pane `B` use `new_split:down` to create `D`

Now notice that if you're in the top right corner (square `B`) and use the `goto_split:left` action it focus the _bottom_ left corner (square `C`) whereas I would expect it to focus the _top_ left corner (square `A`). Similarly, doing `goto_split:right` in `C` takes me to `B` as opposed to `D`. 

So to go from `B` to `A` I need to first go down to `C` and then up to `A`. 

I'm assuming this isn't intentional and in Kitty with the same layout it works as expected (i.e. I can go from `B` to `A` in a single move).  

Now, if you instead split the window into four panes like so (i.e. first create the horizontal split):

1. In pane `A` use `new_split:down` to create `C`
2. In pane `A` use `new_split:right` to create `B`
3. In pane `B` use `new_split:down` to create `D`

Then when you do `goto_split:left` in `B` it takes you to `A` as expected but `goto_split:down` in `B` takes you do `C` as opposed to `D`. 

I hope all that makes sense, it's a bit tedious to explain :) 

## Repro 2

Arguably the correct behaviour for this one is a bit more ambiguous but including anyway for good measure.

First split the window into three panes like so:

```console
┌───┬───┐
│ A │   │
├───┤ B │
│ C │   │
└───┴───┘
```

...with the following actions:

1. In pane `A` use `new_split:right` to create `B`
2. In pane `A` use `new_split:down` to create `C`

Now notice that if you're in `B` and do `goto_split:left` it focues `C` whereas I would expect to focus `A` and in general defaulting to the top pane. It feels natural somehow since the cursor will likely be at the top of B and you expect to see it at the top of `A`. 

## My config

I use keybindings to navigate between splits and here's the minimal config where this issue still occurs:

```
# Navigate window splits
keybind = cmd+shift+h=goto_split:left
keybind = cmd+shift+j=goto_split:bottom
keybind = cmd+shift+k=goto_split:top
keybind = cmd+shift+l=goto_split:right
```

## My environment

Ghostty version: 1.0.0
Ghostty build: 8469
Ghostty commit: 4b4d4062
System: macOS (m1 max)
OS: Sequoia 15.1.1

**Comment by arizon-dread** [comment]
Issue #2866 also details some unexpected split pane navigation behavior, but focuses on the difference between MacOS and Linux. I just wanted to point that out in case somebody ends up here. In Linux, split movement left and top work the same, as well as right and bottom (from what I have been able to detect).

**Comment by dpatterbee** [comment]
Currently there's not a simple "fix" for this. Deciding what split to end up in is not trivial when you consider that splits can be resized and nested arbitrarily.

Issues in this repo are generally for actionable tasks, and this isn't yet actionable so I would recommend this issue gets moved to a discussion for the behaviour to be ironed out before getting reintroduced as an issue.

**Comment by mitchellh** [comment]
Thanks for the detailed writeup, but this is a duplicate as well! It's quite an old issue but if you can find that one and paste your contents there or link this I'd appreciate it ❤

**Comment by eysi09** [comment]
Thanks for the replies! My bad for missing that it's a duplicate, thought I had scoured the older issues but I guess I missed that one (I'm assuming it's #524).
