### ISSUE TITLE
`bold-is-bright` isn't applied to the default foreground color

### ISSUE THREAD

**Issue by kgrusha** [ghostty-org/ghostty#3410]
The `bold-is-bright` setting is apparently not being applied to the default foreground color. The text is bold, but the brightness is not adjusted. If a color is specified explicitly, the brightness will be adjusted.

Repro:
<img width="732" alt="Image" src="https://github.com/user-attachments/assets/9a638849-abb6-4d03-bf04-53bdd280e1e2" />

**Comment by qwerasd205** [comment]
"Bright" refers to the bright variants of the standard palette colors. There is no "bright" equivalent to the default foreground color. It may be a good idea to add that ability to configure one to Ghostty though.

**Comment by kgrusha** [comment]
Fair point! iTerm2 does have a separate option for this specific scenario, and Ghostty could too.

**Comment by mitchellh** [comment]
Closing this. Feel free to open a discussion for a feature request for that though.

**Comment by rnhurt** [comment]
I was just trying to configure Ghostty to replicate my iTerm2 config and ran into this problem.  This shows up in places like `man` pages.  The Ghostty one displays BOLD versions of the font but it's not nearly as pronounced as the iTerm2 display.

## iTerm2
![Image](https://github.com/user-attachments/assets/7523ea84-4ddf-42a2-a294-8ce197744962)


## Ghostty
![Image](https://github.com/user-attachments/assets/0e557a23-dbc7-4eea-ad8d-32e50edd79db)

**Comment by kgrusha** [comment]
@rnhurt There is currently a discussion open as per @mitchellh's suggestion here: https://github.com/ghostty-org/ghostty/discussions/3134 that also has a patch for that.

FWIW, I have written my own implementation yesterday (because the best feature request is a PR 🙃) but I decided to support the one already open to reduce noise. Attaching mine for reference: [foreground-bright.patch](https://github.com/user-attachments/files/18265839/foreground-bright.patch)
