### ISSUE TITLE
macOS Monterey support

### ISSUE THREAD

**Issue by W25X80** [ghostty-org/ghostty#3416]
Please, bring back the macOS Monterey support

**Comment by m4saurabh** [comment]
You can compile it yourself and see if that works.

**Comment by Uzaaft** [comment]
macOS Monterey is EOF as of November 30, 2024.

**Comment by fightingdreamer** [comment]
@W25X80 you can use my branch [ghostty/macos-12](https://github.com/fightingdreamer/ghostty/tree/macos-12) for Monterey.

Can be compiled with pure zig and xcode, as per official docs.

**Comment by mitchellh** [comment]
Thanks @fightingdreamer!

**Comment by W25X80** [comment]
Thank you so much @fightingdreamer!

**Comment by liujhjack** [comment]
> [@W25X80](https://github.com/W25X80) you can use my branch [ghostty/macos-12](https://github.com/fightingdreamer/ghostty/tree/macos-12) for Monterey.你可以使用我的分支 ghostty/macos-12 来支持 Monterey。
> 
> Can be compiled with pure zig and xcode, as per official docs.根据官方文档，可以使用纯 Zig 和 Xcode 进行编译。

hello，Is there a pre-compiled DMG installer available?

**Comment by 00-kat** [comment]
I would recommend directing such questions to that fork's issue tracker, though it appears that issues aren't enabled; @fightingdreamer would you mind enabling issues on your fork so future questions about the fork (rather than upstream Ghostty) can be directed there?
