### ISSUE TITLE
Theme preview palette is black or white when minimum-contrast > 1

### ISSUE THREAD

**Issue by fionn** [ghostty-org/ghostty#3418]
Contents of `$XDG_CONFIG_HOME/ghostty/config`:

```ini
minimum-contrast = 1.1
```

Run `ghostty +list-themes` and notice that the palette colors on the top right are all black or white.

I can reproduce this on macOS (latest) and Linux (Arch).

<details>
<summary>Example screenshots</summary>
<img width="800" alt="3024 Day" src="https://github.com/user-attachments/assets/e5da677c-6205-4b47-9b23-c045b67393c0" /><img width="800" alt="3024 Night" src="https://github.com/user-attachments/assets/066124a5-b363-4745-87a8-ef743d84788d" />
</details>

**Comment by qwerasd205** [comment]
Duplicate of #3074

**Comment by fionn** [comment]
Ah, I missed that, thanks.
