### ISSUE TITLE
shell's default program support? (for tmux)

### ISSUE THREAD

**Issue by GopherJ** [ghostty-org/ghostty#3420]

**Comment by mitchellh** [comment]
I have no idea what you're talking about, please try to be more descriptive

**Comment by monsterhxw** [comment]
My Solution

```config
initial-command = /bin/zsh -l -c "if tmux has-session 2>/dev/null; then tmux attach; else tmux new -s lab; fi"
```

**Comment by GopherJ** [comment]
@monsterhxw thanks, missed `initial-command` I was searching some other keywords..

**Comment by GopherJ** [comment]
> I have no idea what you're talking about, please try to be more descriptive

if the title says already all, I dont think it's necessary to add description...please do check the title

**Comment by pengkai** [comment]
> My Solution
> 
> ```
> initial-command = /bin/zsh -l -c "if tmux has-session 2>/dev/null; then tmux attach; else tmux new -s lab; fi"
> ```

Thanks for your information. I made some changes, and it works fine!

```
command = /bin/zsh -l -c "tmux a || tmux"
```
