### ISSUE TITLE
Wrong cursor size on Wayland

### ISSUE THREAD

**Issue by n0s4** [ghostty-org/ghostty#3429]
My cursor size is much bigger than normal when hovering over a ghostty window on wayland. I would share a screenshot but ksnip doesn't work on wayland, and the issue isn't present on X11.
 
I'm using KDE plasma with the "Breeze" cursor theme, who's sizes come in multiples of 6.

I believe this warning is relevant:

```shell
(process:2358): Gdk-WARNING **: 15:09:44.865: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)
```

**Comment by mitchellh** [comment]
Dupe. GTK bug, fixed in next release. Search for more details.
