### ISSUE TITLE
MacOS - Switching to external display causes text corruption on connect

### ISSUE THREAD

**Issue by djames-bloom** [ghostty-org/ghostty#3436]
### Platform

OS: MacOS
Version: 14.1 (23B74)
SOC: M1 Max 

<details>

<summary>ghostty +version </summary>

```
Ghostty 1.0.0

Version
  - version: 1.0.0
  - channel: stable
Build Config
  - Zig version: 0.13.0
  - build mode : builtin.OptimizeMode.ReleaseFast
  - app runtime: apprt.Runtime.none
  - font engine: font.main.Backend.coretext
  - renderer   : renderer.Metal
  - libxev     : main.Backend.kqueue
```
</details>

<details>

<summary>config</summary>

```
theme = tokyonight
shell-integration = fish
font-family = "Fira Code"
```
</details>

---

### Problem

While Ghostty is running, plugging in an external display, that causes an automatic window position move, between screens causes text to become corrupted. The text rendering returns to normal once the window is moved manually. The same issue appears when unplugging the external display and the window is automatically moved to the remaining display.

This issue has reliably been replicated with every plug/unplug of the external display. 

This has not been observed with any other term I have used (Kitty, Alacritty, iTerm, Hyper)

**Example:**

![Image](https://github.com/user-attachments/assets/582bdde5-2846-4068-8561-947bf1ec5996)

**Comment by mitchellh** [comment]
Dupe.

**Comment by mitchellh** [comment]
Also, resizing or typing a character should workaround this for now (as noted in the dupe)
