### ISSUE TITLE
Vim syntax highlighting in Ghostty

### ISSUE THREAD

**Issue by dlejay** [ghostty-org/ghostty#3446]
`vim -u NONE hello.py`
Then
`:syntax on`

Result in Terminal.app<img width="842" alt="Image" src="https://github.com/user-attachments/assets/9f9a9589-1b43-416a-be2b-caa17a041d63" />

Result in Ghostty<img width="912" alt="Image" src="https://github.com/user-attachments/assets/646a8398-314a-4730-9ea1-40eba77e9e59" />

**Comment by dlejay** [comment]
Ghostty:
* Version 1.0.0
* Build 8469

macOS 15.2

```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov  9 2024 23:15:55)
macOS version - arm64
Included patches: 1-754
Compiled by root@apple.com
```

**Comment by mitchellh** [comment]
Use Q&A if needed. Issues aren't for help.
