### ISSUE TITLE
Linux: `background-opacity` does not change actual window opacity

### ISSUE THREAD

**Issue by SimonYde** [ghostty-org/ghostty#3449]
On Hyprland (wayland), when setting background opacity to anything below 1.0 (e.g. 0.4), it only makes the background brighter, but is not actually becoming transparent.

Kitty with 0.85 opacity above, Ghostty 1.0 opacity below:
![Image](https://github.com/user-attachments/assets/9e9075f2-5068-4548-b0f6-16328f36c73d)

Kitty with 0.85 opacity above, Ghostty 0.4 opacity below:
![Image](https://github.com/user-attachments/assets/5e291a3c-e7b7-4ce2-9b6f-b8b7db8b8d32)

It should be apparent that my desktop background is visible behind Kitty but not behind ghostty.
I have no special window rules set in Hyprland for kitty nor for ghostty.

**Comment by znycheporuk** [comment]
Likely duplicate of https://github.com/ghostty-org/ghostty/issues/3324

**Comment by SimonYde** [comment]
yes this is a duplicate of #3324, closing
