### ISSUE TITLE
Shell completion is invisible with `OneHalfDark` theme

### ISSUE THREAD

**Issue by d-hain** [ghostty-org/ghostty#3450]
When using the `OneHalfDark` theme shell completions are not visible:
Default theme:
![Image](https://github.com/user-attachments/assets/42b4b589-412e-4b8e-90a7-34d3e92c5753)

`OneHalfDark` theme:
![Image](https://github.com/user-attachments/assets/0b1b647d-9378-45e4-ae71-a5e2ef8796b7)
(here the cursor is also not visible for some reason)

WezTerm for comparison:
![Image](https://github.com/user-attachments/assets/ce18472b-9bcc-4714-9eb0-e49bff8f53b4)

(when pressing the right arrow key all of these complete as expected)

**Comment by mitchellh** [comment]
Upstream: https://iterm2colorschemes.com

**Comment by X1r0z** [comment]
I encountered the same problem.

You can just copy the original `OneHalfDark` theme configuration and change the RGB value of one of the palettes

```bash
mkdir -p ~/.config/ghostty/themes
cp /Applications/Ghostty.app/Contents/Resources/ghostty/themes/OneHalfDark ~/.config/ghostty/themes/OneHalfDarkModified
```

diff

```diff
< palette = 8=#282c34
---
> palette = 8=#666666
```

I changed it to `#666666` (maybe it's not the best color)

Now the shell completions are visible

<img width="370" alt="Image" src="https://github.com/user-attachments/assets/e47afa10-730a-486d-bba1-b26b1a9ea908" />

**Comment by threddast** [comment]
I have this issue with both OneHalfDark and OneHalfLight

**Comment by gugahoi** [comment]
This was also the case for `LiquidCarbonTransparent`. The solution above works well.
