### ISSUE TITLE
maximum nested function level reached

### ISSUE THREAD

**Issue by devashishraj** [ghostty-org/ghostty#3453]
Getting warning of 
`azhw:zle-line-finish:3: maximum nested function level reached; increase FUNCNEST?`

default FUNCNEST value is 700 and this does not cause any warning in default terminal or wezterm

zsh version 5.9
macOS 15.2

<img width="1257" alt="Image" src="https://github.com/user-attachments/assets/4726782b-0bee-4ceb-9cf7-37c36004f76f" />

**Comment by mitchellh** [comment]
This looks like it might be a zsh shell integration issue. cc @anund @jparise ?

**Comment by anund** [comment]
@devashishraj looks like wezterm takes a different approach to shell-integration to ghostty/kitty. If I read the docs right they ask users to add to their `.zshrc`. ghostty attempts to inject functions automatically by changing modifying the init for zsh.

To see if you've got a simple fix: run ghostty with `--shell-integration=none` to see if you still have the error. Then you can try `--shell-integration=none` + manually source the integration (similar to wezterm) https://ghostty.org/docs/features/shell-integration#manual-shell-integration-setup

If that fixes your case we'll have to figure out what your specific zsh startup process and how it might interact with https://github.com/ghostty-org/ghostty/blob/bee21880149129f9373a35e9df0d39c223481709/src/shell-integration/zsh/.zshenv

**Comment by devashishraj** [comment]
> [@devashishraj](https://github.com/devashishraj) looks like wezterm takes a different approach to shell-integration to ghostty/kitty. If I read the docs right they ask users to add to their `.zshrc`. ghostty attempts to inject functions automatically by changing modifying the init for zsh.
> 
> To see if you've got a simple fix: run ghostty with `--shell-integration=none` to see if you still have the error. Then you can try `--shell-integration=none` + manually source the integration (similar to wezterm) https://ghostty.org/docs/features/shell-integration#manual-shell-integration-setup
> 
> If that fixes your case we'll have to figure out what your specific zsh startup process and how it might interact with https://github.com/ghostty-org/ghostty/blob/bee21880149129f9373a35e9df0d39c223481709/src/shell-integration/zsh/.zshenv

i am not facing the error without shell integration and without shell integration with manual integration .
Also i am using p10k and ohmyzsh

**Comment by anund** [comment]
Thank you. There must be a loop in the init process then. If you don't mind, we'll have to walk your zsh init as I don't have p10k or ohmyzsh installed. 

- what value is your `ZDOTDIR`
- if you can share your `.zshenv` and `.zshrc` that would be helpful

**Comment by devashishraj** [comment]
@anund i have not set ZDOTDIR and value after manual integration is also null

my .zshrc (removed some alias) 

https://gist.github.com/devashishraj/3354a90c99bbdd725f3673261ea8934d

**Comment by anund** [comment]
Hmm, a lot of config in there I'd have trouble reproducing from scratch. Can you go through a cycle of commenting things out until the bug goes away? I can see if just powerline + ohmyzsh reproduces the issue in parallel.

**Comment by mitchellh** [comment]
Thanks anund and sorry for the misunderstanding I thought this was already actionable :)
