### ISSUE TITLE
write_scrollback_file doesn't include what's on the current screen

### ISSUE THREAD

**Issue by Tenzer** [ghostty-org/ghostty#3496]
First off, great work on the achievement of this project!

The `write_scrollback_file` action was suggested in https://github.com/ghostty-org/ghostty/issues/189#issuecomment-1824543708 to be an alternative to the currently missing scrollback search functionality.

When testing this out, I however noticed it's only contents of the scrollback which is outside of the current screen which get written to the file, which means - if you want to search through the scrollback - you will only be able to search through the lines which are not visible on the screen.

Is this intended? Would it not be better to output everything in the scrollback, including what is visible on the current screen?

I can't think of a use case where you'd only want the contents that aren't visible on the screen to be written in the file.

As a quick way of testing this, you can open a new tab, enter `for i in $(seq 1 100); do echo $i; done` to print out numbered lines, and then perform the `write_scrollback_file` action by pressing `super + shift + j` and notice it doesn't include all the lines outputted from the loop.

**Comment by mitchellh** [comment]
`write_screen_file` is what you want. `write_scrollback_file` only writes the _scrollback_ (not the active screen)

**Comment by Tenzer** [comment]
Sorry! Right after creating this, I noticed the `write_screen_file` ([link](https://ghostty.org/docs/config/keybind/reference#write_screen_file)) action is available which does include the contents of the current screen.

**Comment by jcollie** [comment]
FWIW, `write_screen_file` and `write_scrollback_file` are absolutely _awful_ names for these operations given what they do. I think that we should re-open this issue as a springboard to rename them and to change the default keybinding.

**Comment by mitchellh** [comment]
This is the terminology we use internally:

https://github.com/ghostty-org/ghostty/blob/1fa2e699d142b9bc2795a4d3db98b035cc5a825c/src/terminal/point.zig#L6-L48

**Comment by mitchellh** [comment]
I’m not trying to suggest it. I’m just posting it as information.
