### ISSUE TITLE
quick terminal support splits, add on website

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3518]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3318

<div type='discussions-op-text'>

<sup>Originally posted by **AnirudhG07** December 26, 2024</sup>
Hey! Thanks for the amazing ghostty!
I was reading the docs and I never saw any place where it states that quick terminal supports splitting into panes, it does not support tabs which is present, but some people who want to use different tabs can atleast benefit from the fact that you know open splits!(kind of like a reminder) 
Is it possible if I can add it [here](https://ghostty.org/docs/config/keybind/reference#toggle_quick_terminal) in the documentations for the website??
Thanks!</div>

**Comment by AnirudhG07** [comment]
Hi I have a PR regarding the same.
Please suggest any changes there itself! Thank you so much!!!

**Comment by mitchellh** [comment]
That PR should be on the Ghostty repo or it'll get reverted. that file is auto-generated.

**Comment by AnirudhG07** [comment]
Oh I see. Mb. Is there anything I should do now cause the PR is merged?

**Comment by mitchellh** [comment]
Oh this was done. Thanks
