### ISSUE TITLE
1Password CLI integration not working

### ISSUE THREAD

**Issue by jksolbakken** [ghostty-org/ghostty#3521]
When I attempt to use the [1Password CLI integration](https://developer.1password.com/docs/cli) I get an error message: `No accounts configured for use with 1Password CLI.`. The CLI integration is turned on in 1Password and works in iTerm2 and Alacritty.

**Comment by jksolbakken** [comment]
Never mind, I hadn't answered "yes" to the "use data from other apps" permission in macOS

**Comment by TechDufus** [comment]
@jksolbakken  Whenever I run any `op` commands (whether directly, using the terraform 1Password provider, etc...) I get this popup... Do you not?

![Image](https://github.com/user-attachments/assets/59cfb5ba-85c2-432d-a0be-3f238adb95a5)

**Comment by gummy789j** [comment]
same issue here.
