### ISSUE TITLE
macOS: default `cmd+9` binding should be `last_tab`, not `goto_tab`

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3528]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3361

<div type='discussions-op-text'>

<sup>Originally posted by **Samasaur1** December 27, 2024</sup>
This is a combination of a question about changing the default behavior and something that is kind of bug-like.

#### Behavior

In Terminal.app and every other Mac app I can think of, ⌘9 goes to the last tab instead of the 9th tab when more than 9 tabs exist. In Ghostty, however, ⌘9 selects the 9th tab in that scenario.

#### Bug

I was able to override this behavior with
```
keybind = command+nine=last_tab
```
but this did not change the little hints that Ghostty inserts for each tab:
<img width="1512" alt="screenshot of the tab bar with 10 tabs showing" src="https://github.com/user-attachments/assets/5eedcb95-c720-41cd-9642-af0cf5a3ede8" />

#### Next steps

I'm not really sure what exactly I'm asking for here. Mostly I guess I'm saying that I'm surprised that ⌘9 *didn't* go to the last tab with no configuration, since that's the "usual" Mac app behavior. It would also be nice if the hints in the tab bar updated if you set keybindings like I have done, although I imagine that the current hints are hardcoded and getting this to work would be a not insignificant amount of work for very little benefit.</div>

**Comment by crahan** [comment]
I think the default key bindings add to the confusion here as well. 

```
keybind = super+physical:zero=last_tab
keybind = super+zero=reset_font_size
```

In my case on a US layout, the `reset_font_size` key binding wins and overrides the`last_tab` key binding.

I think `super+zero=reset_font_size` makes sense (next to - and + for font resize on a US layout), so maybe the default binding for `super+physical:nine` should become `last_tab` as you noted to help resolve this key binding conflict as well?

![Image](https://github.com/user-attachments/assets/bbad1c40-101c-496f-a030-53847c265268)

**Comment by Samasaur1** [comment]
Yes, ⌘0 should be reset font size by default
