### ISSUE TITLE
Quick terminal characters mangled

### ISSUE THREAD

**Issue by kmatt** [ghostty-org/ghostty#3532]
Mac M3 Sequoia 15.2

Often when bringing the quick terminal up the characters are briefly mangled / scrambled. The screen capture command key sequence resolves it, so had to capture with a phone.

```
Last login: Fri Dec 27 13:10:45 on ttys007
~/SHC/projects > fwd-etl
Opening tunnel on port: 2222
Tunnel is ready, connect on port 2222
Ctrl + C to close
```
appears as:

![Image](https://github.com/user-attachments/assets/dd424c34-e044-48fb-914d-04d90bbae3a2)

---

Config:

```
font-family = "Fira Code Regular"
font-size = 15
keybind = global:cmd+`=toggle_quick_terminal
quick-terminal-animation-duration = 0.1
```

**Comment by mitchellh** [comment]
Dupe. Please search!

**Comment by kmatt** [comment]
#2731
