### ISSUE TITLE
Linux/Wayland: Big cursor

### ISSUE THREAD

**Issue by prochac** [ghostty-org/ghostty#3545]
Ghostty is not the first or the last app that has problems on Wayland when it involves scaling. In my case, it's 150%.

I would be very happy to help more than posting screenshots, but when it comes to X11/Wayland, I have no deep knowledge what's going on.

![Image](https://github.com/user-attachments/assets/6cb93ddb-7ab1-417e-9a7b-0e465c8a4ad3)
![Image](https://github.com/user-attachments/assets/ae3947b7-8a20-42eb-a6c6-cb2b5fadf3df)
![Image](https://github.com/user-attachments/assets/9a6c6e7e-f9b6-431a-bcdd-e4e273a67c5f)

**Comment by mitchellh** [comment]
Search. This is a dupe reported so many times over the past 24 hours. Its a GTK bug.

**Comment by prochac** [comment]
Sorry 🤦, I promise I tried to search first, but wrong keywords, I guess.

**Comment by seasonedfish** [comment]
If anyone comes across this looking for a workaround, [here's the discussion thread](https://github.com/ghostty-org/ghostty/discussions/3167) where workarounds are discussed.
