### ISSUE TITLE
Macos, how to search for a text?

### ISSUE THREAD

**Issue by Edweis** [ghostty-org/ghostty#3546]
I feel a bit stupid for asking this one, but how do you search for a text in the terminal on macOs?

I tried `{keys} + F` and looked in the documentation and I can't find the feature.

**Comment by mitchellh** [comment]
Search, see pins, etc. Its everywhere!

**Comment by vodium-vastro** [comment]
See https://github.com/ghostty-org/ghostty/issues/189

**Comment by Edweis** [comment]
Thank you for your prompt response.

@mitchellh , What do you mean?


> See [#189](https://github.com/ghostty-org/ghostty/issues/189)
Thanks, any other way I can search without using `{keys} + F` ?

**Comment by yankcrime** [comment]
@Edweis Until #189 is implemented, you need to either use a terminal multiplexer such as tmux or zellij which provide support for searching their buffers, or rely on [action_scrollback_file](https://ghostty.org/docs/config/keybind/reference#write_scrollback_file).

**Comment by fruizg0302** [comment]
@Edweis Thank you for asking this as I'm the same position, interacting a lot with a Rails console and doing a cmd + f when I need to find a specific record.

**Comment by ivanglushko** [comment]
Without CMD+F it  doesn't feel native

**Comment by mitchellh** [comment]
> Without CMD+F it doesn't feel native

That's why we have an open issue. Follow #189. Closing this since all discussion should go to #189.
