### ISSUE TITLE
ssh problem

### ISSUE THREAD

**Issue by mo-cherif** [ghostty-org/ghostty#3549]
ssh not working correctly

**Comment by mitchellh** [comment]
Please be more descriptive, use the Q&A section, and search. I have no idea what the problem is because you don't describe it at all.

**Comment by phillip-haydon** [comment]
> Please be more descriptive, use the Q&A section, and search. I have no idea what the problem is because you don't describe it at all.

@mitchellh I'm replying here because I cannot create a new issue, it wants to open a discussion which is a bit dumb.

The issue is when you ssh into a server (on macOS atleast) if you want to move the cursor or delete anything, it literally doesn't work. 

![Image](https://github.com/user-attachments/assets/5a6b378a-b1b0-4e09-a980-e1070eb3d9ba)

**Comment by mitchellh** [comment]
Open a Q&A discussion. That’s what it’s there for. 

This question has been answered maybe 50 times the past week. You can search and find your answer easily

**Comment by phillip-haydon** [comment]
> Open a Q&A discussion. That’s what it’s there for.
> 
> This question has been answered maybe 50 times the past week. You can search and find your answer easily

I searched issues, this was the one that popped up.

**Comment by mitchellh** [comment]
Search discussions. Issues are for bugs. Not for support

**Comment by mitchellh** [comment]
I’m sorry to be terse but this is very well documented in a pinned issue and our contributing guide. If I responded to everyone as an exception it’d be unsalable (there’s been 600 Q&A posts in 1 week). We must lean on the rules.

**Comment by phillip-haydon** [comment]
> Issues are for bugs

But this is a bug? This is broken out of the box, I'm unsure why I have to work-around an bug to get it working... Totally understand not wanting support/feature requests polluting the issues, and having discussions around features to not rush implementation. But if downloading Ghostty and then it breaks immediately when you SSH into a server, that has to be a bug... 

In any case I'm glad its known and hope it gets fixed. I'm definitely not smart enough dig into this and fix it or contribute anything of value other than raising attention to this.

**Comment by mitchellh** [comment]
It's not a bug, explained: https://github.com/ghostty-org/ghostty/discussions/3583#discussioncomment-11755097

**Comment by mitchellh** [comment]
(Locking this issue because issues aren't for discussion, feel free to use the discussion)
