### ISSUE TITLE
Japanese IME pre-edit does not display on GTK backend on Wayland

### ISSUE THREAD

**Issue by sin-ack** [ghostty-org/ghostty#3551]
Ghostty version: 1.0.0
System: Gentoo Linux x86_64
Rendering backend: GTK
Font rendering: Fontconfig+Freetype
libadwaita: Enabled
Display: Wayland (Hyprland)
IME: fcitx 5.1.11

Ghostty currently doesn't render Japanese IME input until the input is accepted by pressing Enter or letter:

![Image](https://github.com/user-attachments/assets/94ccbaa7-d559-4c71-992f-0a642f6dd84b)

![Image](https://github.com/user-attachments/assets/f9e71996-ae2a-4857-9258-770aa4ad56ca)

Expected behavior (using Kitty):

![Image](https://github.com/user-attachments/assets/d70546ce-667a-4838-8f8f-d922ec5f68c1)

![Image](https://github.com/user-attachments/assets/5fa8d1ec-0774-4e3a-ac9b-da339907bcd6)

**Comment by mitchellh** [comment]
Thanks, there is a dupe for this currently in issue triage.

**Comment by sin-ack** [comment]
Um, what is the original issue..? I tried "japanese", "ime" and "pre-edit" which didn't bring up anything, which is why I opened the issue.
