### ISSUE TITLE
macOS: exiting fullscreen does not restore background-opacity

### ISSUE THREAD

**Issue by HannesOlszewski** [ghostty-org/ghostty#3553]
When entering fullscreen mode with `cmd-ctrl-f` the background is not transparent anymore, as expected. But when I exit fullscreen mode the same way again, the original `background-opacity` value is not restored, or at least the background is not transparent anymore.

### Before fullscreen
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/344f5a4f-2694-4e38-ae1c-9925b602a35b" />

### Fullscreen
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/ee93f73f-5b2e-4986-a21c-dc65fbba279f" />

### After exiting fullscreen
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/141e1204-681e-42cb-a380-14a20a4a1e9c" />

## Config
Device: MacBook Pro 13" M1
OS: Macos 15.2
Version: Ghostty 1.0.0

`~/.config/ghostty/config`:
```
background-opacity = 0.7
background-blur-radius = 20

window-padding-x = 8
window-padding-y = 8
window-colorspace = display-p3
macos-titlebar-style = hidden
macos-icon = custom-style
macos-icon-frame = plastic
macos-icon-ghost-color = ffffff
macos-icon-screen-color = 262335
command = /bin/zsh -c /opt/homebrew/bin/zellij

foreground = ffffff
background = 262335
cursor-color = ffffff
selection-foreground = ffffff
selection-background = 262335

palette = 0=#262335
palette = 1=#fe4450
palette = 2=#72f1b8
palette = 3=#f3e70f
palette = 4=#03edf9
palette = 5=#ff7edb
palette = 6=#03edf9
palette = 7=#ffffff
palette = 8=#614d85
palette = 9=#fe4450
palette = 10=#72f1b8
palette = 11=#fede5d
palette = 12=#03edf9
palette = 13=#ff7edb
palette = 14=#03edf9
palette = 15=#ffffff
```

**Comment by jay-dee7** [comment]
I can definitely reproduce this one Macos and I suspect `background-opacity` is being overwritten on fullscreen. This happens in both of the following scenarios:
1. Builtin shortcut `CTRL+CMD+f` 
2. Using the fullscreen toggle button from title bar

Also, just reloading the config makes it blur again

**Comment by gigamonster256** [comment]
> [@mitchellh](https://github.com/mitchellh) this is not a GTK issue. It is only occurring on Mac. I wonder if it is a dupe of [#3324](https://github.com/ghostty-org/ghostty/issues/3324).

I just tried it with https://github.com/ghostty-org/ghostty/pull/3347 checked out and the opacity not being restored when exiting native fullscreen.

**Comment by a7mdDev** [comment]
FWIW
It appears the fullscreen style is being nulled out when exiting fullscreen [here](https://github.com/ghostty-org/ghostty/blob/d5703a57e7d7bcf8dd9bd5711d9f351e5a43446b/macos/Sources/Features/Terminal/BaseTerminalController.swift#L316). This happens before it receives the `didExitFullscreenNotification` thus never really handling it.

@gigamonster256's fix moves the ownership of listening to the fullscreen toggle from FullscreenStyles to `TerminalController` which I'm assuming is a more permanent thing, and is not really deinitialized in a similar manner.
