### ISSUE TITLE
Incorrect kerning offsets for subsets of Unicode

### ISSUE THREAD

**Issue by 0x4D5352** [ghostty-org/ghostty#3554]
First noticed it with Starship's git status indicators:

Ghostty
<img width="292" alt="Image" src="https://github.com/user-attachments/assets/d96bb107-97d1-4382-aaef-5b9470485199" />

Alacritty
<img width="294" alt="Image" src="https://github.com/user-attachments/assets/8b7214a0-4342-4fa1-8274-16fabfffbdce" />

Happens on all the dashed arrows, screenshots below show the misaligned cursor offset for dashed-left and dashed-up. 
<img width="265" alt="Image" src="https://github.com/user-attachments/assets/bace123d-95f0-482e-a0b4-68f308a0a263" />
<img width="259" alt="Image" src="https://github.com/user-attachments/assets/ae7016ad-48c8-4403-9cad-6c75e1491099" />
<img width="261" alt="Image" src="https://github.com/user-attachments/assets/b568e4af-0d75-46f5-b9a2-6059afe146b2" />
<img width="280" alt="Image" src="https://github.com/user-attachments/assets/112669f5-729b-400f-b376-d95af47ae5c3" />
<img width="273" alt="Image" src="https://github.com/user-attachments/assets/22117aed-7033-4450-a08e-6c019ef0594f" />
<img width="267" alt="Image" src="https://github.com/user-attachments/assets/9ba9df5f-61d7-42ba-867e-62e6bd019ca2" />

Likely occurs for other Unicode values, but I haven't had a chance to test more extensively.

**Comment by mitchellh** [comment]
Dupe #3541
