### ISSUE TITLE
macOS Natural Text Editing: "command delete" should delete whole line, not one character

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3646]
Discussion: #3232 

Add: `keybind = cmd+backspace=esc:w` as a default for macOS. This is similar to #3106.

**Comment by mitchellh** [comment]
Note: this may have to be `\x15`. Me or whoever does this should do some research to figure out the right input here.

**Comment by datwaft** [comment]
`\x15` is working for me. https://github.com/datwaft/dotfiles/blob/16504b331bffaa6b56f65012132330c2124323b8/.config/ghostty/config#L12

**Comment by mitchellh** [comment]
Fixed by #3679
