### ISSUE TITLE
Inconsistent Dot Spacing in Text Files Edited with Vim

### ISSUE THREAD

**Issue by adamsoliev** [ghostty-org/ghostty#3657]
**Config:**
```
window-width=180
window-height=50
```

MacOS Version 15.1.1

**Steps to reproduce:**
1. Open Ghostty
2. Open a txt file using vim
3. Type 3 dots, delete all and type back 4 dots

**Expected Behavior:** 
Consistent spacing between dots.

**Actual Behavior:** 
Spacing varies as the number of dots increases from 1 to 4.

https://github.com/user-attachments/assets/d6e697ad-8ade-4ff3-bc00-df1dd06fe43d

**Comment by mitchellh** [comment]
These are ligatures. Use help to learn more. Issues are not support

**Comment by rdlugosz** [comment]
@adamsoliev Here's what you need to add to your config file to disable ligatures:
```
font-feature = -calt
font-feature = -liga
font-feature = -dlig
```

There's some [ongoing discussion](https://github.com/ghostty-org/ghostty/discussions/3323) about this topic; hth future web searchers.
