### ISSUE TITLE
write_selection_file on macOS does not work properly

### ISSUE THREAD

**Issue by newtonapple** [ghostty-org/ghostty#3678]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3594

<div type='discussions-op-text'>

<sup>Originally posted by **newtonapple** December 27, 2024</sup>
I'm on MacOS macOS Sequoia 15.2 with default text editor TextEdit.  This is my ghostty config file:

```
copy-on-select = true
focus-follows-mouse = true

# keybinds
keybind = super+f=write_screen_file:open
keybind = super+shift+f=write_selection_file:open
```

`write_selection_file` doesn't seem to work properly.  

When I select multiple lines, the file TextEdit opens is empty. 
<img width="1325" alt="selection_txt_and____config" src="https://github.com/user-attachments/assets/11135688-1712-49cb-abf1-d28f2f1a5737" />

But when I select one word, the text in the selection.txt is the entire line. 
<img width="1303" alt="Cursor_and_selection_txt_and____config" src="https://github.com/user-attachments/assets/d053b9bd-b20b-4e73-be4c-744381a15297" />

Also tried it with `write_selection_file:paste`, the contents in the temp files were the same as the ones in screenshots.
</div>

**Comment by mitchellh** [comment]
Use discussions. Issues are only for maintainers to create.
