### ISSUE TITLE
Wierd window stretch when using a tiling wm (linux, wayland, gtk)

### ISSUE THREAD

**Issue by M4rti21** [ghostty-org/ghostty#3682]
Whenever i resize the windows or create new windows (which makes the existing ones resize) i get this weird stretches. It doesnt happen if i do a "normal" mouse resize, where its a "smooth" resize, it only happens on a tiling window manager where resizes are "jumps". 

https://github.com/user-attachments/assets/c993c0d8-eb31-4da2-baba-ea06fd29ae1e

- Build: `ghostty 1.0.0-3` from the Arch Linux repository.
- OS: Artix Linux
- WM: dwl (wayland wlroots)
- Backend: pretty sure its libadwaita...

My config:
```conf
foreground = "C5C9C5"
background = "12120f"
background-opacity = 0.95
background-blur-radius = 15

theme = "Kanagawa Dragon"

font-family="IBM Plex Mono Medium"
font-family-bold="IBM Plex Mono Bold"
font-family-italic="IBM Plex Mono Medium Italic"
font-family-bold-italic="IBM Plex Mono Bold Italic"

window-decoration = false
window-save-state = "never"
window-padding-balance = true
window-padding-y = 8
window-padding-x = 8

resize-overlay = "never"

clipboard-read = allow
clipboard-write = allow
clipboard-paste-protection = false

confirm-close-surface = false
quit-after-last-window-closed = true

gtk-single-instance = true
gtk-titlebar = false

bold-is-bright = true
```

**Comment by mitchellh** [comment]
Not approved yet by maintainers. Only maintainers open issues.

**Comment by M4rti21** [comment]
oh mb, i was not aware that was the case!
