### ISSUE TITLE
Request: Quake-style (Visor) Overlay Terminal Mode

### ISSUE THREAD

**Issue by yoshimi-I** [ghostty-org/ghostty#3689]
# Feature Request: Quake-style (Visor) Overlay Terminal Mode

**Summary**  
I would love to have a “Quake-style” or “Visor-style” overlay mode in Ghostty. In this mode, the terminal would slide down from the top of the screen (overlaying other application windows) and hide again with a keybind. This would allow me to quickly access the terminal while keeping my current applications visible underneath.

---

## Motivation / Use Case
- Quickly reference code, logs, or commands without leaving full view of other apps.  
- Maintain focus on other windows while still having a terminal readily available.  
- Similar to iTerm2’s “Visor” feature or the “Quake-style” terminal used in many Linux environments.

---

## Proposal
1. **Configuration/Flag:**  
   Add a new configuration option (e.g., `quick-terminal-mode = "visor"`) or a CLI flag like `--overlay`.  
2. **Behavior:**  
   When enabled, pressing a global keybind (e.g., `Shift + Enter`) would animate the terminal sliding down from the top edge of the screen and remain on top of other applications.  
3. **Toggle:**  
   Pressing the same keybind again would hide the terminal back to the top.  
4. **Optional Opacity:**  
   Ideally, allow transparency so the user can see underlying apps if desired.

---

## Additional Details
- The current `quick-terminal` feature is close, but it behaves as a normal window rather than truly overlaying.  
- This feature would mimic a “visor” effect, letting the user see and interact with other apps behind the translucent terminal.  
- Some macOS permissions (Accessibility) may be required for global overlays.  
- Could be macOS-only initially or made cross-platform if feasible.

---

## Benefits
- **Enhanced Productivity:** Useful for developers who rapidly switch between code editors, browsers, and terminals.  
- **Reduced Friction:** Eliminates constant window arrangement or switching for quick terminal commands.

---

## Thank You
Adding an overlay-style terminal would make it even more powerful for everyday use.

**Comment by yankcrime** [comment]
This already exists, see https://ghostty.org/docs/config/keybind/reference#toggle_quick_terminal

**Comment by mitchellh** [comment]
Issues aren't for feature requests.
