### ISSUE TITLE
no config: `theme = tokyonight`

### ISSUE THREAD

**Issue by mefengl** [ghostty-org/ghostty#3715]
`theme = tokyonight`

This theme fits better with the website and icon's style.

> It's also the default theme in dhh's `omakub`, see https://omakub.org/#whats-the-dress-code

_Originally posted by @mefengl in https://github.com/ghostty-org/ghostty/discussions/2363#discussioncomment-11671218_

**Comment by mitchellh** [comment]
No previous discussion where it was accepted by a maintainer.
