### ISSUE TITLE
Configuration Reload Fails on Mac

### ISSUE THREAD

**Issue by assemble-code** [ghostty-org/ghostty#3769]
Discussion Number:
Subsequent Configuration Reload Fails on Mac Machine.

Steps
1. Make an invalid key value pair entry in the config file
2. Reload the terminal and we get an error, if we click on `ignore` then any changes we do after that to the config file is never reloaded again.

I tried restarting the Mac, completely killing the Terminal but nothing works.

**Comment by mitchellh** [comment]
This is not an approved issue. There’s no discussion. Please follow the rules! Thank you

**Comment by assemble-code** [comment]
Sorry, I wasn't aware about the discussion.
