### ISSUE TITLE
Is it possible to remove a ghostty icon from a dock on MacOS?

### ISSUE THREAD

**Issue by frolvanya** [ghostty-org/ghostty#3854]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3810

<div type='discussions-op-text'>

<sup>Originally posted by **frolvanya** December 28, 2024</sup>
<img width="65" alt="image" src="https://github.com/user-attachments/assets/48ebbe44-fa1c-4e8d-85a7-6fb7ffbe4bd0" />

I'm using ghostty primarily in quick-terminal mode, so I don't want to see an icon in the dock</div>

**Comment by mitchellh** [comment]
Only maintainers create issues
