### ISSUE TITLE
Feature request: Splits equalizing on splitting

### ISSUE THREAD

**Issue by jonathanj** [ghostty-org/ghostty#3861]
(I'm posting this as an issue, since the discussion appears to have gone unanswered, maybe 2 weeks wasn't long enough? Apologies if so.)

### Discussed in https://github.com/ghostty-org/ghostty/discussions/2947

<div type='discussions-op-text'>

<sup>Originally posted by **jonathanj** December 12, 2024</sup>
In https://github.com/ghostty-org/ghostty/issues/831 the `equalize-splits` command was added, I'd like to suggest going one step further: Have an option to automatically equalize splits after splitting. iTerm 2 splits behave this way by default.

There are some quirks to equalizing though, for example if I do: split right, split right, split bottom, split right:

<img width="1713" alt="image" src="https://github.com/user-attachments/assets/ea0dc1e8-1105-4754-a956-68e080315c9c" />

If I equalize splits now, I would expect that my right splits each become 1/3 wide, and my bottom split becomes 1/2 high, however that's not quite what happens:

<img width="1713" alt="image" src="https://github.com/user-attachments/assets/773dea1d-7587-4d6a-a193-27527a25ea19" />

The right splits are not divided equally into thirds, and the bottom split is not divided equally into halves. I'm not sure I can understand what happened, but it wasn't what I was expecting. If I modify my sequence slightly in ghostty, it will produce the same thing as iTerm 2: split right, split right, equalize splits, split bottom, split right

For reference, this is what my sequence of splits produces in iTerm 2:

<img width="1714" alt="image" src="https://github.com/user-attachments/assets/3c367c26-2804-4f51-9c8a-6862b02a63df" />
</div>

**Comment by JakeWharton** [comment]
https://github.com/ghostty-org/ghostty/issues/2227#issuecomment-2564602539

**Comment by jonathanj** [comment]
Thanks for the discussion link, knowing it was a conscious decision helps, and the proposal in #2227 sounds good.

My expectation comes from iTerm2 and vim, which behave similarly, although Ghostty behaves like tmux (which I seldom use). I see I'm [not the only person who had different expectations](https://github.com/ghostty-org/ghostty/discussions/3839), some  clarification in the splitting docs could help.
