### ISSUE TITLE
`scrollback-limit` should be `usize`

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3900]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3884

<div type='discussions-op-text'>

<sup>Originally posted by **lopopolo** December 29, 2024</sup>
Results in a config parsing error:

```
scrollback-limit = 4294967296
```

Success:

```
scrollback-limit = 4294967295
```

Since this parameter directly influences allocating memory, I'd expect it to be bounded by `size_t`, or maybe something like Rust's `isize::MAX` which echos the LLVM max allocation size.</div>

**Comment by aw1875** [comment]
Correct me if I'm wrong but this change seems like it would only be in the context of the config as it looks like the terminal already expects the `max_scrollback` to be a usize

**Comment by mitchellh** [comment]
That's my understanding, the type system will confirm all that for you though.

**Comment by aw1875** [comment]
Cool thanks! Gonna take a look at this one!
