### ISSUE TITLE
Bengali text's weird behavior in neovim

### ISSUE THREAD

**Issue by yishao0925** [ghostty-org/ghostty#3915]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3912

<div type='discussions-op-text'>

<sup>Originally posted by **yishao0925** December 30, 2024</sup>
1. In normal mode, press $ to go to the end of the text, but the cursor doesn't show at the end of the text.
https://github.com/user-attachments/assets/4f99df79-498d-4d5b-bef9-5780d6b7e179
2.In view mode, select the text and press d to cut, the remain text is not correct.
https://github.com/user-attachments/assets/4ec462d3-7350-40d7-82a6-395dd579dea2

</div>

**Comment by mitchellh** [comment]
Only maintainers make issues
