### ISSUE TITLE
macOS: `open_config` action should prefer AppSupport over XDG

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3953]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3952

Our priority when loading configs is well documented: https://ghostty.org/docs/config#macos-specific-path-(macos-only):

But `open_config` does the opposite. This makes it too easy for people to have configs that are being overridden without them realizing it.

We should swap the logic in `open_config`.

**Comment by TeriyakiBomb** [comment]
I had a look at #3952 and related to #3820 and I think this might still cause a bit of confusion.

When first installing and clicking around - ⌘, or app menu -> Settings and you get the default behavior of opening in textedit. Presumably at this point it created the config file in $HOME/Library/Application\ Support

It then becomes a little unclear what is happening without a subsequent visit to the docs. All a bit edge case-ey admittedly but after creating a config file in ~/.config/ghostty would make ⌘, a bit redundant?
