### ISSUE TITLE
macOS: QuickTerminal under certain circumstances spins at 100% CPU

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#3998]
### Discussed in https://github.com/ghostty-org/ghostty/discussions/3723

<div type='discussions-op-text'>

<sup>Originally posted by **stuartcarnie** December 28, 2024</sup>
Noticed that Ghostty was using 100% CPU, so I grabbed a CPU profile under Instruments and found that the hottest call stack was related to the Quick Terminal feature:

![img](https://cdn.discordapp.com/attachments/1322555981103632447/1322560293984800789/CleanShot_2024-12-28_at_06.41.142x.png?ex=677151c2&is=67700042&hm=44d828e85fe45540883b199ea6eb5aa50c8b57efc89d9871f6a158982b63ce4c&)

When I drill into that stack, `QuickTerminalController.syncAppearance` is a hot function. I currently don't have the window open, and I believe the culprit is this code:

https://github.com/ghostty-org/ghostty/blob/196af6f2ca7221b38ee14c8f286cc99e0a7108fa/macos/Sources/Features/QuickTerminal/QuickTerminalController.swift#L310-L318

Given the window isn't open, this will repeatedly call the `syncAppearance` function. 

> [!NOTE]
>
> Re-opening the Quick Terminal reduces the CPU to nominal levels again.

To re-trigger the high CPU usage, force a reload of your configuration and watch it spike again.</div>

**Comment by mitchellh** [comment]
We should flag a pending sync appearance and wait for the window to become visible (via notifications) to apply it.

**Comment by divs1502** [comment]
Hi, I was just visiting through the code trying to understand the bug what I believe we should check again if self is still valid before calling syncAppearance 

`DispatchQueue.main.async { [weak self] in
        if let self = self {
            self.syncAppearance(config)
        }
    }`

**Comment by mitchellh** [comment]
That would probably work but if we can avoid queueing up multiple that'd be ideal, so I think we should fix this in a more robust way.

**Comment by divs1502** [comment]
Yes, correct then using the flag to prevent queuing multiple sync calls and avoiding unnecessary CPU usage spikes.

**Comment by dmehala** [comment]
I observed this behavior and called it here https://github.com/ghostty-org/ghostty/pull/3742, however I didn't thought it was that bad and was hoping to get some feedback to address it directly in the PR. However, @mitchellh, I can understand that it might be better to address the performance issue separately.

**Comment by pijvari** [comment]
> Hi, I was just visiting through the code trying to understand the bug what I believe we should check again if self is still valid before calling syncAppearance
> 
> `DispatchQueue.main.async { [weak self] in if let self = self { self.syncAppearance(config) } }`

Hmm, does this code change any behaviour? as the original code `DispatchQueue.main.async { [weak self] in self?.syncAppearance(config) }` have optional chaining in `self?.syncAppearance...` it wouldn't call `syncAppearance` anyway if self is nil?

**Comment by divs1502** [comment]
> > Hi, I was just visiting through the code trying to understand the bug what I believe we should check again if self is still valid before calling syncAppearance
> > `DispatchQueue.main.async { [weak self] in if let self = self { self.syncAppearance(config) } }`
> 
> Hmm, does this code change any behaviour? as the original code `DispatchQueue.main.async { [weak self] in self?.syncAppearance(config) }` have optional chaining in `self?.syncAppearance...` it wouldn't call `syncAppearance` anyway if self is nil?

Yes you are correct although this does not explicitly change any code behavior but this will help maintain readability and avoid multiple calls ( if we need to perform multiple actions that depend on self, using if let self avoids repeating self? ).
