### ISSUE TITLE
Linux system theme - dbus ReadOne not implemented

### ISSUE THREAD

**Issue by leigholiver** [ghostty-org/ghostty#4038]
On my system (pop-os 22.04 LTS) with system theme and seperate light and dark themes, ghostty always defaults to light mode. Switches between light and dark mode are properly handled.

In the logs this error is reported:
```
error(gtk): unable to get current color scheme: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “ReadOne”
```

The spec notes that the other functions are "[Deprecated, use ReadOne instead.](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html)" so using ReadOne is certainly the correct path.

I've managed to fix this on my system by checking for the error and falling back to an implementation using the deprecated Read.

Issue discussion: https://github.com/ghostty-org/ghostty/discussions/3704
Fix PR: https://github.com/ghostty-org/ghostty/pull/4035

**Comment by mitchellh** [comment]
Fixed by #4035
