### ISSUE TITLE
Unknown terminal type in multipass shell

### ISSUE THREAD

**Issue by anyon17** [ghostty-org/ghostty#4155]
On my mac I am doing `multipass shell dev-vm` through the ghostty terminal. When I try to `clear` it says
```
'xterm-ghostty': unknown terminal type.
```
Also when inside a git repo when I do `git branch`, it says
```
WARNING: terminal is not fully functional
Press RETURN to continue
```

**Comment by mitchellh** [comment]
Issues are not for help

**Comment by anyon17** [comment]
how would I know if this is a real issue or I just need help ?

**Comment by mitchellh** [comment]
Read CONTRIBUTING.md or the pinned issue. Your answer is there

**Comment by anyon17** [comment]
Ohh okay, much thanks @mitchellh for the direction, will check it out.

**Comment by danquack** [comment]
I stumbled upon this issue as well. Although the direction of this project is to move to discussions, here’s a link to the discussion that helped me solve it. https://github.com/ghostty-org/ghostty/discussions/4077

**Comment by mfilipav** [comment]
I resolved the same issue by copying local Ghostty's `terminfo` to a remote machine, as described in the documentation: https://ghostty.org/docs/help/terminfo#copy-ghostty's-terminfo-to-a-remote-machine
